### ISSUE TITLE
ImageRow, allow taking photo

### ISSUE THREAD

**Issue by weyert** [xmartlabs/Eureka#101]
What's the best approach to allow picking a photo or taking a photo. In most application it first shows an action sheet where you can pick Take Photo or Choose Photo only I don't know what the best approach to implement this? I am currently using ImageRow which looks wonderfully well.

**Comment by mtnbarreto** [comment]
if we only want to take a photo we can use `onPresent` as the code below shows.
```swift
                <<< ImageRow(){
                        $0.title = "ImageRow"
                    }
                    .onPresent({ (form, imagePickerController) -> () in
                        imagePickerController.sourceType = .Camera                    })
```
--------------

I like the idea of showing a action sheet to select if open a camera, the photo library or SavedPhotosAlbum. 

```swift
public enum UIImagePickerControllerSourceType : Int {
    case PhotoLibrary
    case Camera
    case SavedPhotosAlbum
}
```
What about adding a OptionSetType property to specify which SourceType options the action sheet should display. (Action Sheet should not be displayed if the OptionSetType contains only one option).

`_ImageRow` extends from `SelectorRow<T: Equatable, VCType: TypedRowControllerType>`. We will have to override its `customDidSelect` method in order to display the actionSheet and move the overridden code (code that present the imagePickerViewController) to the UIAlertController action block.

**Comment by weyert** [comment]
Looks like you are suggesting to first display an action sheet before displaying the image picker controller based on the source type. I will give this a shot.

**Comment by mtnbarreto** [comment]
@weyert great! looking forward to seeing your pull request!

**Comment by weyert** [comment]
@mtnbarreto I have created a pull request. Let me know, what you think of it in the PR.

**Comment by weyert** [comment]
Done :)
