### ISSUE TITLE
Hiding sections/rows condition mistake in code

### ISSUE THREAD

**Issue by heisen273** [xmartlabs/Eureka#1013]
First of all, - great library, thank you for this.

I was using the lib and I've found out that, for some reason, logical AND and OR operations are misplaced, for some reason.
Here is example:
I want to show a date_row ONLY If row with tag1 and tag2 are not false:
here is wat I set
`date_row.hidden = "$tag1 == false && $tag2 == false"`

In result, date_row will be shown if ANY of tag1 or tag2 rows are clicked. 

When you set date_row hiding like this:
`date_row.hidden = "$tag1 == false || $tag2 == false"`

I get expected result(date_row shown only if tag1 and tag2 are clicked)

Not 100% sure, but it looks to me that some-one accidentally mis-coded logical operators.

**Comment by m-revetria** [comment]
Hi @heisen273, 

That looks like the expected behavior to me. If you want to show a date_row only if rows with $tag1 and $tag2 are not false you should use:

```swift
hidden = "$tag1 == false || $tag2 == false"
```

If you set your row's hidden property with `"$tag1 == false && $tag2 == false"`, then it will be **hidden** only when **both conditions are satisfied** which is the same to it will be **shown** if **at least one of both conditions is not satisfied**.

`hidden = "$tag1 == false && $tag2 == false"` would be the same to `visible = "$tag1 == true || $tag2 == true"` (if `visible` would exist 😄 ). So if you touch either one of rows tag1 or tag2, and its value changes to true, then the date_row will be shown.

Cheers

**Comment by heisen273** [comment]
i might be wrong, mate, thanks for your feedback anyways.
