### ISSUE TITLE
Trying to use FormController as a subview in a pushedView (from NavigationController item) results in loss of notifications for keyboard

### ISSUE THREAD

**Issue by chefren** [xmartlabs/Eureka#1045]
# Environment
- Eureka = 3.0.0
- Xcode = 8.3.2
- iOS version = 10

# Scenario - also on [SO](http://stackoverflow.com/posts/43994002/edit)
- NavigationController is a root controller of a TabBarController
- TabBarController has 2 UIViewControllers
- One UIViewController has a function that presents another UIViewController
- UIVIewController that is presented has a StackView
- Instantiates a subclass of FormController (eg: FormVC) and adds to Stack as subview

## Symptom
Input fields added
<img width="372" alt="screen shot 2017-05-16 at 4 42 19 pm" src="https://cloud.githubusercontent.com/assets/2918150/26093336/d3d3128e-3a58-11e7-86ce-0132337d84aa.png">
When trying to input, the scroll is not working and the field remains covered by the keyboard
<img width="364" alt="screen shot 2017-05-16 at 4 42 30 pm" src="https://cloud.githubusercontent.com/assets/2918150/26093338/d6474260-3a58-11e7-89e5-188c5cb13fe9.png">

It is more evident as the mentioned `keyboardWillShow` method is not called (tried overriding it and setting a breakpoint)

# Problem
The `keyboardWillShow` function of FormVC does not get called. The keyboard actually adds the input to the row, but the auto scrolling does not happen

Is this only a problem in Eureka or perhaps a problem using the Navigation controller's `pushViewController`?
## Possible hint
When making the FormController the direct Controller of the pushed view I also get this error and the app crashes.
```
NSForwarding: warning: object 0x6080000d76f0 of class 'Eureka.Form' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[Eureka.Form initWithCoder:]
```

**Comment by chefren** [comment]
Here is a sample project with a Nav controller, and a TabBar controller that pushes the Form VC view container.
[TestEureka.zip](https://github.com/xmartlabs/Eureka/files/1010186/TestEureka.zip)


You can see the keyboardWillShow methods and check that if not called by the View that pushes it, they are not passed.

I also run into another problem in this scenario, related to hiding rows. You can replicate as in the gif
![eureka_hide_crash](https://cloud.githubusercontent.com/assets/2918150/26192533/70bd4360-3bf5-11e7-900e-44c3595edd51.gif)

**Comment by m-revetria** [comment]
Hi @chefren the problem with your approach is that the `FormViewController` lifecycle is not being handled because you are not adding it to the view controllers hierarchy. Actually you are only adding its view to one of your views.

The function `keyboardWillShow` is not being called due to the `FormViewController` adds this observer to the notification `Notification.Name.UIKeyboardWillShow` from the function `viewWillAppear`, which in your case is not being called. As this, other stuff may not work properly, because the view controller lifecycle is not being handled.

That is not the way the `FormViewController` should be used. Using it in that way may end up with an undesired behavior like you experienced. The correct way to embed a `FormViewController` in other view controller's view is by adding it as a Child View Controller. See this Apple guide for further information [Implementing a Container View Controller](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html). Additionally, in storyboards you can use a `Container View`s.

Regards

**Comment by chefren** [comment]
Thank you Miguel, I figured that out and commented here: https://stackoverflow.com/q/43994002/1736679. Will add it as proper answer and close this now :)

**Comment by chefren** [comment]
ps: I still get warnings like these when using the Container VC

```
System group container for systemgroup.com.apple.configurationprofiles path is /Users/..../Library/Developer/CoreSimulator/Devices/3CF3987A-27..../data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-05-23 11:06:23.185924+...[MC] Reading from private effective user settings.
```

Are those expected?
