### ISSUE TITLE
How do I assign tag for Selectable Section? duplicate error.

### ISSUE THREAD

**Issue by kaka21garuda** [xmartlabs/Eureka#1061]
So I have a selectableSection in the ViewDidLoad:

```swift
+++ SelectableSection<ListCheckRow<String>>("Pick your state", selectionType: .singleSelection(enableDeselection: true))
        
        let states = [ "AK - Alaska", "AL - Alabama", "AR - Arkansas"]

for option in states {
            form.last! <<< ListCheckRow<String>(option){ listRow in
                listRow.title = option
                listRow.selectableValue = option
                listRow.value = nil
            }
        }
```
and I also have a reference with a tag as a public variable: 
```swift
let state: ListCheckRow<String>? = Form().rowBy(tag: "stateRow")
```
PROBLEM: Now I know that I will have multiple rows with the same tag, which is not allowed. that's why I always have this error `assertion failed: Duplicate tag listOfStatesRow: file /Users/bukacakrawala/` because of this test: 
```swift
assert(section.form?.rowsByTag[t] == nil, "Duplicate tag \(t)")
```
what should I put in the tag? in order for me to get the selected row.

**Comment by fedeojeda95** [comment]
Hi @kaka21garuda 

I can't see a problem with having duplicate tags in your code. Actually, your code is very similar to the one in the example which is working correctly. The error is saying that there is already a row with the tag `listOfStatesRow`. May it be that you are setting that tag to two rows in another part of the code? I can't see that you are using that tag in this part of the code. 

About getting the value of the selectable section, in the line: `let state: ListCheckRow<String>? = Form().rowBy(tag: "stateRow")` why are you creating a new `Form`? You should use the same form instance to which the sections and rows were added. Also, when you are getting the row by the tag, the tag won't be `"stateRow"` but there will be a row with a different tag for each state ("AK - Alaska", "AL - Alabama", "AR - Arkansas")

In order to get the selected value of the section, you can use the method `.selectedRow()` in order to get the selected row. Then, you can use the property `baseValue` to get the value that was selected. 

For example:

    let optionsSection = SelectableSection<ListCheckRow<String>>("Pick your state", selectionType: .singleSelection(enableDeselection: true))
        
        let states = [ "AK - Alaska", "AL - Alabama", "AR - Arkansas"]

        for option in states {
            form.last! <<< ListCheckRow<String>(option){ listRow in
                listRow.title = option
                listRow.selectableValue = option
                listRow.value = nil
            }
        }

    form +++ optionsSection

    //to get the value
    print(optionsSection.selectedRow().baseValue)

If you do something everytime the value changes, you could override the method `func valueHasBeenChanged(for row: BaseRow, oldValue: Any?, newValue: Any?)` from `FormViewController`. For further info, please check the example project.

Hope it helps! Feel free to ask anymore questions. Regards,

**Comment by kaka21garuda** [comment]
the reason why I did this:
```swift
let state: ListCheckRow<String>? = Form().rowBy(tag: "stateRow")
```
is because I want to access the value in different method. I did that with all the other row (Textrow) that I made, and it works perfectly fine. Also in the example, I couldn't find any tag assignment in the selectable row.

**Comment by kaka21garuda** [comment]
so I have this public variable:
```swift 
let optionsSection = SelectableSection<ListCheckRow<String>>("Pick your state", selectionType: .singleSelection(enableDeselection: true))
```
and in the viewDidLoad():
```swift 
let states = [ "AK - Alaska", "AL - Alabama", "AR - Arkansas"]

for option in states {
   form.last! <<< ListCheckRow<String>(option){ listRow in
      listRow.title = option
      listRow.selectableValue = option
      listRow.value = nil
    }
}

form +++ optionsSection
```

but now the problem is: whenever I chose a row in the selectable row, it somehow not choosing. there is not tick. as a result my value is always nil.

**Comment by santiagofm** [comment]
Hey @kaka21garuda ! The issue there is the order in which you are appending the rows and the `SelectableSection` to the form. You are appending the rows to the last section and then **after** that you are appending the `optionsSection` to the form. It should be the other way around.

```swift
form +++ optionsSection

let states = [ "AK - Alaska", "AL - Alabama", "AR - Arkansas"]
for option in states {
   form.last! <<< ListCheckRow<String>(option){ listRow in
      listRow.title = option
      listRow.selectableValue = option
      listRow.value = nil
    }
}
```

**Comment by m-revetria** [comment]
Closing this due to lack of response
