### ISSUE TITLE
Can't access current row in Condition.function()

### ISSUE THREAD

**Issue by AlexandreMinard** [xmartlabs/Eureka#1078]
Hello,

I don't know how to access the current row in a Condition.function,
except by getting it from the form.rowBy(tag) method.

My problem is that I don't know the tag of my row, I build it while creating the rows.
Look at my code below, you'll understand my problem.

```swift
var cpt = 0
<<< CheckRow() {
    $0.tag = "product_\(cpt)" // cpt is 0
    $0.title = "title"
    $0.hidden = Condition.function([])
    { form in
        let row = form.rowBy(tag: "product_\(cpt)")! // cpt is 1 when this function is evaluated
        return true
    }
}
cpt = 1
```

How can I solve that?

Thanks in advance.

Regards,
Alexandre

**Comment by m-revetria** [comment]
Hi @AlexandreMinard,

In this case you can capture the reference to the row that is passed to the creation block. A small change in your code should solve the problem:

```swift
var cpt = 0
<<< CheckRow() { row in
    row.tag = "product_\(cpt)" // cpt is 0
    row.title = "title"
    row.hidden = Condition.function([])
    { form in
        // `row` is the current row
        return true
    }
}
cpt = 1
```

-------------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `eureka-forms`.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
