### ISSUE TITLE
Custom PickerInputRow

### ISSUE THREAD

**Issue by appamericanassist** [xmartlabs/Eureka#1085]
Hi!
How I create a PickerInputRow using nib file?

@mtnbarreto help me plis

**Comment by m-revetria** [comment]
Hi @appamericanassist please refer to the documentation here https://github.com/xmartlabs/Eureka#custom-rows, and the blogs here https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/ and here https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/ (in the example shown here a nib file is used). You may find something useful in these questions in StackOverflow https://stackoverflow.com/search?q=%5Beureka-forms%5D+custom+row.

------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `eureka-forms`.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
