### ISSUE TITLE
Freeze Sections and Rows

### ISSUE THREAD

**Issue by tobib89** [xmartlabs/Eureka#1138]
I'd like to be able to fix the position of certain rows and section titles in the tableview.

I'd like the header to stay at the top of the screen as the user scrolls up. It would then move out of the way when the user scrolls far enough that the next section would take its place.

```swift
Section()
        
<<< TextRow("FixedRow") {
           $0.title = "Test"
}

form +++ Section("HeaderTitle1")
<<< TextRow("Text1") {
                $0.title = "Test"
        }
<<< TextRow("Text2") {
                $0.title = "Test"
        }
....
form +++ Section("HeaderTitle2"
```

Is it possible to freeze the first row ("FixedRow") and the actual section title at the top of the tableview?

**Comment by mtnbarreto** [comment]
Hi, you can stick the section header using a Plain UITableView  instead of a grouped UITableView. Table view rows can not have a fix position at the top of the screen by default since it work like any table view row.
Maybe you can create a create a custom header and add a UITextField to it taking advantage of the fixed header. Take into account the `UITextField` delegates and value should be handled manually by you. Eureka doesn't know anything about custom headers apart from display them. 

For more information about custom headers take a look at https://github.com/xmartlabs/Eureka#custom-view .
