### ISSUE TITLE
i want to use a button to validate the form 

### ISSUE THREAD

**Issue by pprevalon** [xmartlabs/Eureka#1155]
I want to use a button to validate the form. When the form is validate i want to change the placeholder color. I use validate() but where do i put row.placeholderColor = .red

**Comment by pprevalon** [comment]
how do i change the font color. I see i can change the placeholder color but not the font color

**Comment by m-revetria** [comment]
Hi @pprevalon please refer to the Validation section in the readme https://github.com/xmartlabs/Eureka#validations. Consider using rules for your rows and in that case you have to implement the cell update as bellow:

```swift
.cellUpdate { cell, row in
  if !row.isValid {
    cell.titleLabel?.textColor = .red
  }
}
```

------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `eureka-forms`.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
