### ISSUE TITLE
Custom row design

### ISSUE THREAD

**Issue by Urkman** [xmartlabs/Eureka#1156]
What is the best way to change the design of a row?
Lets say, I want to add some paddings and borders...

**Comment by AchidFarooq** [comment]
Maybe this will help you?
https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/

**Comment by m-revetria** [comment]
Hi @Urkman, you are able to perform some changes like setting labels font, textColor, backgroundColor and so on. You can achieve this kind of changes by implementing the callback `cellSetup` for the desired row and modifing the appropriate values. Take snippet below as an example:

```swift
EmailRow("email") { row in 
  row.title = "Email"
}.celSetup { cell, row in
  cell.textLabel?.font = .boldSystemFont(ofSize: 24)
}
```

If you want to apply the same changes to all rows instances of some type you can use the `defaultCellSetup` callback:

```swift
EmailRow.defaultCellSetup { cell, row in
  // Apply all the needed style changes here. Them will be applied to all instances of EmailRow
}
```

In order to achieve a deeper change on a native Eureka's row design, you have to create a new xib file with the design you want and make the outlets to the cell's controls (labels, textfields, etc., depending on the selected row).

You can refer to the documentation here https://github.com/xmartlabs/Eureka#custom-rows and next blog https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/ for further information.

You may find something useful in these questions in StackOverflow https://stackoverflow.com/search?q=%5Beureka-forms%5D+custom+row.

------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `eureka-forms`.

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
