### ISSUE TITLE
Cannot update SliderRow minimumValue and maximumValue

### ISSUE THREAD

**Issue by Iambecomeroot** [xmartlabs/Eureka#1158]
## Environment:
* Eureka: 3.0.0
* Xcode: 8.3.3 (8E3004b)
* iOS: 10.3

## Problem:
I am trying to dynamically update a `SliderRow`'s `minimumValue` and `maximumValue` properties. My slider row looks like this:

```swift
<<< SliderRow("value") {
    $0.title = "Value"
    $0.minimumValue = 0
    $0.maximumValue = 100
    $0.disabled = .function(["state"], { ($0.rowBy(tag: "state") as? SegmentedRow<State>)?.value != .manual })
    $0.displayValueFor = {
        guard let setting = self.state.setting else { return String(describing: $0) }
        return String(format: "%.1f%@", $0 ?? setting.minValue, setting.units)
    }
}
```

I later update it after another row changes like this:

```swift
value.minimumValue = setting.minValue
value.maximumValue = setting.maxValue
value.title = "Test title"
value.reload()
value.updateCell()
```

I know something is happening because the title changes but I can still drag the slider above and below `setting.minValue` and `setting.maxValue` which are `5.0` and `35.0` in this case.

**Comment by m-revetria** [comment]
Hi @Iambecomeroot, this seems to be an issue to me. The problem is that the row's `minimumValue` and `maximumValue` are not synced with the underline slider in the cell. Those values are only used when the cell is setup.

Until this issue is solved, as a workaround, you can set the `minimumValue` and `maximumValue` to the cell's slider directly. But take into account that this may cause other issues on your app. This is due to the slider's value may change but the row's value will stay the same.

In your example, if you at start the row's value is `0` and then you change the slider's minimumValue to be `10`, then the slider's value will be changed to `10` but the row's value will stay `0`. So you will need to **properly set the row value after that change**.

**Comment by Iambecomeroot** [comment]
Thanks. I will try that at work tomorrow. When I change the min/max its because the setting is changing (%/temperature) and when this happens I default the slider to the minimum value so it should not be an issue.

**Comment by Iambecomeroot** [comment]
The workaround is working.

**Comment by mtnbarreto** [comment]
@m-revetria  What about moving the set up of these slider properties from cell setup to cell update?
As an alternative, we can completely delete these properties to avoid any confusion.

> I would go for the first solution that doesn't break anything.
