### ISSUE TITLE
Unable to refresh a section with .hidden Conditions

### ISSUE THREAD

**Issue by DuncanACampbell** [xmartlabs/Eureka#1244]
I have a section on one of my forms which has a switch.  If the switch is ON, we show two more cells, and if the switch is OFF we hide those two cells - using a .hidden Condition.

All I'm looking to do is reload that section when the view appears with the latest data, but I can't get the conditions to reevaluate.  Or if they do, the screen doesn't reload to show the two cells.  

Is there a standard way I should be handing this?  i.e. .hidden should be in the .cellUpdate block?  Or I should remove all rows from the section and add the again?

Thanks everyone.  Awesome library.

**Comment by eliburke** [comment]
#1212 has a feature request to add e.g. section.evaluateHiddenRows()

For now, if the section is always visible, but has cells that are conditionally hidden, the simplest solution is to call cell.evaluateHidden() for each cell. 

I have found another technique that also works, though I have it commented as a "hack" in my code 😄. If your Conditionals are set to observe the value of another row, and you change the row's value, all observers will re-evaluate their hidden and disabled state. 

```
        detailsRow = CustomRow("Details") { ... }

        ...
        
        titleRow = LabelRow("Title") { row in
            ....
            row.hidden = Condition.function(["Details"], { form in
                    return self.someBooleanValue
            })
        }

        let value = detailsRow.value
        detailsRow.value = nil
        detailsRow.value = value
```

The value needs to actually change otherwise it won't work (you can see the logic in [Row.swift](https://github.com/xmartlabs/Eureka/blob/ec14ae696e82d4e4bbc82c767336da0e37a39ce1/Source/Core/Row.swift#L29-L50))

**Comment by mats-claassen** [comment]
To force evaluate the `hidden` condition for a section you can do the following:

```swift
section.forEach { row in
            row.evaluateHidden()
            row.updateCell()
        }
```

**Comment by eliburke** [comment]
section.forEach { } does not seem to work for this purpose. It appears as though hidden rows are not included in the forEach sequence.

**Comment by mats-claassen** [comment]
Sorry, you are right. `section.forEach ` includes visible rows only.

You could loop over `form.allRows` if it is ok for you to re-evaluate all rows of the form, or you could filter `form.allRows` like this:
`form.allRows.filter { $0.section == someSection }.forEach {}`
