### ISSUE TITLE
Disabling and Enabling Row not update

### ISSUE THREAD

**Issue by JonathanImperato** [xmartlabs/Eureka#1303]
I have 2 different rows in a section:
```swift
        form
            +++ Section("Visita di ritorno"){
                $0.tag = "sezione"
            }
            <<< TextAreaRow(){ row in
                row.title = "Informazioni Trattate"
                row.placeholder = "Inserire le informazioni trattate qua"
                row.tag = "infotrattate"
                row.value = data.0
                row.disabled = true
                }
            <<< DateInlineRow(){
                $0.title = "Data contatto"
                $0.value = Date()
                $0.tag = "data"
                $0.disabled = true
                $0.value = dateResult
                }
```

on a click of my UIBarButtonItem i want to make them enabled, i am doing it in this way:
```swift      
        let InfoRow: TextAreaRow? = form.rowBy(tag: "infotrattate")
        let dataRow: DateInlineRow? = form.rowBy(tag: "data")
        let sezione: Section? = form.sectionBy(tag: "sezione")
        InfoRow?.disabled = false
        dataRow?.disabled = false
        InfoRow?.reload()
        dataRow?.reload()
        sezione?.reload()
```

But it is not working. What is wrong?

**Comment by ClayApps** [comment]
I am see the same also:
let submitRow: ButtonRow = form.rowBy(tag: "SubmitButtonRowTag")!
submitRow.disabled = true
form.sectionBy(tag: "SubmitSectionTag")?.reload()

**Comment by m-revetria** [comment]
Hi @JonathanImperato, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

That being said, you have to call `evaluateDisabled` function in order to reflect the changes to the `disabled` property. 

```swift
let InfoRow: TextAreaRow? = form.rowBy(tag: "infotrattate")
InfoRow?.disabled = false
InfoRow?.evaluateDisabled()
```

> https://github.com/xmartlabs/Eureka#row-does-not-update-after-changing-hidden-or-disabled-condition

**Comment by m-revetria** [comment]
I'm closing this due to lack of response
