### ISSUE TITLE
How can I change single row seprator color during validation?

### ISSUE THREAD

**Issue by ERbittuu** [xmartlabs/Eureka#1356]
I want to change current line separator color during validation of field.

**Comment by m-revetria** [comment]
Hi @ERbittuu, you have to check in the `cellUpdate` block if the row is valid or not and change the UI according.

How to change the `line separator color`? It depends a lot on the row that you are using. If you are using the defaults rows then you cannot change the line separator color just for one row due to form uses `UITableView`'s separator and it is a global property (for all cells in the table).

If you're using custom rows, use next code as snippet and update your cell's UI according.

```swift
.cellUpdate { cell, row in
    if !row.isValid {
       // Access to your cell's separator line and change its color
    }
}
```

---------------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag `eureka-forms`.

**Comment by ERbittuu** [comment]
I am using default separator,
Now trying with the custom cell.

Thanks,
