### ISSUE TITLE
set Row "hidden = false" is not work when hidden was true?

### ISSUE THREAD

**Issue by hopy11** [xmartlabs/Eureka#1384]
hi everyone!

I set Row "hidden = true" in row's init block:

```
<<< ImageRow("image"){ row in
    row.hidden = true
}
```

and I want display the row when user interactive with another row:

```
anotherRow.onChange{row in
    let imageRow:ImageRow = self.form.rowBy(tag: "image")!
    imageRow.hidden = false
    imageRow.reload()
}
```

but it's not working... imageRow is always hidden...
I know I can use bool value related with anotherRow to do that:

```
imageRow.hidden = "$anotherRow  != true"
```

But my related value's type is not bool ：

```
struct UserLogo:Equatable{
    var image:UIImage?
    var showChooseRow:Bool = false
}
```

I try to use below code , but it's not working too...

```
imageRow.hidden = Condition.function([]){form in
                        let logoRow:UserLogoRow = form.rowBy(tag: "anotherRow")!
                        if let userVal = logoRow.value{
                            return !userVal.showChooseRow
                        }else{
                            return true
                        }
                    }
```

How to fix this ??? thank you ;)

**Comment by m-revetria** [comment]
Hi @hopy11, as it is pointed out in the [Contributing guidelines](https://github.com/xmartlabs/Eureka/blob/master/CONTRIBUTING.md#asking-questions) we don't use Github issues for general library support. In such cases, the best option is posting questions on StackOverflow with tag `eureka-forms`. 

This will help us to better manage real bugs and feature requests and also we think you'll get better and faster support for this kind of questions from community through StackOverflow.

-------------------

That being said, you have to call `evaluateHidden` function in order to reflect the changes to the `hidden` property. 

```
anotherRow.onChange{row in
    let imageRow:ImageRow = self.form.rowBy(tag: "image")!
    imageRow.hidden = false
    imageRow.evaluateHidden()
}
```

**Comment by hopy11** [comment]
OK! I know!

thanks a lot whatever！
