### ISSUE TITLE
Clear DateRow

### ISSUE THREAD

**Issue by marbetschar** [xmartlabs/Eureka#139]
How do clear a DateRow after a date was selected?

**Comment by marbetschar** [comment]
Any Info about this?

**Comment by blue-toe** [comment]
See issue #103.

**Comment by mtnbarreto** [comment]
@marbetschar There may be many ways to clear or reset a row. This is a UI dependent task and Eureka lets everyone choose how to do it. 
**Eureka was originally designed to be flexible and extensible and was not intended to cover all look and feel and style scenarios out of the box**

This are some solutions i have in mind:

1. Updating `navigationAccessoryView ` as #103 points out.
2. Adding a section footer that display a extra action to reset a row. 
3. Long press gesture, swipe gesture. (I don't like this approach since it's not intuitive).
4. Making use of cell `accessoryView` or `imageView` to show a additional action.
