### ISSUE TITLE
Fix Usage in readme

### ISSUE THREAD

**Issue by ylecuyer** [xmartlabs/Eureka#14]
The Usage part in the readme is wrong.

It should explain that you must create a ViewController with a tableview inside (style grouped) and a referencing outlet to the FormViewController owned by the UIViewController.

Moreover, example rows (WeekdayRow, FloatLabelRow) are non standard rows, the should be replaced by IntRow and TextRow for instance.

**Comment by SpacyRicochet** [comment]
> It should explain that you must create a ViewController with a tableview inside (style grouped) and a referencing outlet to the FormViewController owned by the UIViewController.

None of this should be necessary, right? After creating a new Single View App, the only change I introduced was installing Eureka as a CocoaPod and adding some lines of code to the `viewDidLoad()` (see code below). The `Main.storyboard` hasn't been changed.

```
import UIKit
import Eureka

class ViewController: FormViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        form = Form()
        form +++ Section()
        form.last! <<< TwitterRow("Twitter") { row in
            row.title = "Twitter Row"
            row.placeholder = "twitter username"
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

**Comment by ylecuyer** [comment]
It works like that but you can't manage the view from the storyboard. I
extracted the steps I explained before from the example app that is bundled
into the repo

**Comment by SpacyRicochet** [comment]
Noted. Still, the README isn't so much wrong as that it could use an extra section explaining how to initialise a proper FormViewController from a Storyboard. You're probably welcome to write one :)

I'm actually wondering why you would want to manage the FormViewController's at all from a Storyboard. Seems like a FormViewController is rather specifically tied to being its own delegate and dataSource and wouldn't work otherwise. 

@mtnbarreto @mats-claassen Is there a specific reason for using Storyboards here (or at all)?

**Comment by mtnbarreto** [comment]
I agree on that WeekdayRow, FloatLabelRow are non-standard rows and we should have chosen native ones to the example so i made clear this in the readme.

Regarding the Storyboard issue I think you can infer that  a FormViewController can be created either programatically or using a Storyboard like any other UIViewController and in case of using a storyboard you have the ability to connect the tableView outlet, if not a default table view will be created and positioned into the screen using its frame property.

@SpacyRicochet we have created the forms through storyboard because it's easier to add layout constraints to its table view and set up a right position to it taking into account the top and button layoutMargin. The table view position created by default doesn't work property in all scenarios (forms embedded in tabBarController, NavigationController, forms with margins, forms that don't fill all the screen, etc).

Nothing stops us to do it programatically, just i think it's easier using storyboards and the developers are familiar with how storyboards works.

@ylecuyer @SpacyRicochet thanks for reporting the library usage misunderstanding and helping me out improving the doc.

Regards
