### ISSUE TITLE
How to reduce the code

### ISSUE THREAD

**Issue by githubhero** [xmartlabs/Eureka#1424]
Not an issue, sorry, just a question: I have a form with ten DecimalRows. They share the same code (same cellUpdate events, etc.). Is there any way to reduce the code, e.g. creating a class that extends DecimalRow and write my events only once?

**Comment by mats-claassen** [comment]
Yes you can obviously extend a row or you can use a simple `for` loop to reduce the lines of your code

**Comment by mtnbarreto** [comment]
Hi @githubhero ! you can use `defaultCellSetup`, `defaultCellUpdate` and `defaultRowInitializer` that applies to all row instances instead of a particular row instance. 

These callbacks are invoked before its correspond instance version, for example `defaultCellSetup` is invoked before `cellUpdate`.

Please take a look at related issues to understand how to use them.
