### ISSUE TITLE
[Suggestion] Add titlePercentage to TextAreaRow

### ISSUE THREAD

**Issue by AnsonT** [xmartlabs/Eureka#1464]
FieldRows have titlePercentage, but TextAreaRows do not. It would be nice to add that to TextAreaRows to align text area fields with other input fields.

**Comment by vitoflorko-swiftdev** [comment]
Can I work on this? I would like to implement this feature

**Comment by mats-claassen** [comment]
@vitoflorko-swiftdev Sure, you can work on this. Remember to leave the default behavior of the TextAreaRow as it is now.

**Comment by vitoflorko-swiftdev** [comment]
So let me ask about this just so I know that I've implemented this correctly. I have added a titlePercentage property, which allows you to decide essentially how much space is occupied by the textView portion of the TextAreaCell, same as the FieldRow. So for example in your ExampleApp: titlePercentage = 0.5:

<img width="349" alt="screenshot 2018-10-30 at 22 37 35" src="https://user-images.githubusercontent.com/25185916/47752311-66a28e80-dc94-11e8-911e-d33d0ad6a9eb.png">

I'm only asking because the FieldRows in the ExampleApp have left and right elements inside the cell. TextArea is just a textArea. Is this the correct behavior? If not please elaborate and I will rework the functionality :)

**Comment by mats-claassen** [comment]
As @AnsonT mentioned, this feature might be interesting to align the TextView with text fields in other cells. Therefore the textview should leave space on the left of the cell if `titlePercentage`  is set. 

So it you set `titlePercentage` to 0.4 in a `TextAreaRow` then the textView should be aligned to a textField in a `TextRow` with `titlePercentage` set to 0.4

The placeholderLabel should not be affected by this.

**Comment by vitoflorko-swiftdev** [comment]
Ah, now I think I understand. 

So essentially what we're talking about is, when we have a TextRow and a separate TextAreaRow, and I set the titlePercentage of the TextAreaRow to 0.4 as well as in some TextRow above it, both textfields get aligned?

**Comment by mats-claassen** [comment]
Exactly

**Comment by vitoflorko-swiftdev** [comment]
So I managed to do the following:
When we have:
`
<<< TextAreaRow() {
                $0.placeholder = "TextAreaRow"
                $0.value = "aadhwiuhdiuahwdiuhawiudhawiudhaiuwfiuafiuawhfawfawdawawdaddiuawhdiuahwd"
                $0.textAreaHeight = .dynamic(initialTextViewHeight: 110)
                $0.titlePercentage = 0.4
            }

            <<< TextRow() {
                $0.title = "TextRow"
                $0.placeholder = "aadhwiuhdiuahwdiuhawiudhfawgawawgawdawiudhaiuwfiuafiuawhdiuawhdiuahwd"
                $0.titlePercentage = 0.4
            }
`

then we get:

<img width="384" alt="screenshot 2018-11-01 at 16 42 12" src="https://user-images.githubusercontent.com/25185916/47862287-17c03a80-ddf5-11e8-83bd-a5061e1b9b35.png">

At 0.65 for example we get:

<img width="383" alt="screenshot 2018-11-01 at 16 42 56" src="https://user-images.githubusercontent.com/25185916/47862337-31618200-ddf5-11e8-8a01-cebc7a0227a2.png">

Is this what we want? :)

**Comment by vitoflorko-swiftdev** [comment]
I have left a pullrequest and we can discuss it there if you agree :)

**Comment by mats-claassen** [comment]
The pull request has been merged into master. Use version 4.3.1

**Comment by nicolopadovan** [comment]
This seems to have some trouble when using a placeholder for the TextAreaRow.
