### ISSUE TITLE
Custom datePicker  ( picker view )

### ISSUE THREAD

**Issue by douglasd3** [xmartlabs/Eureka#15]
Hello, is there any way to the datePicker shows only year? This is a constraint in UIDatePicker class and maybe would be a great functionality for Eureka.

**Comment by mtnbarreto** [comment]
@douglasd3 As you said there is a datePicker constraint that don't allow us to make use of DateRow or similar row. 

It seems to me that this is a specific case of a picker view selector that we want to implement shortly.
Picker view selector row will allow us to set a collection of dates and configure the displayValueFor in order to show only the year of the NSDate. 
Alternatively we can set up the picker view selector row with a collection of strings that represent each year to be selected.

Every Eureka selector row is a generic type so it can be initialized to hold any type.
Regards.

**Comment by mtnbarreto** [comment]
Now Eureka contains `PickerRow` and `PickerInlineRow` rows.
