### ISSUE TITLE
How to create a CountDownInlineRow with minutes and seconds? feature: PickerView supporting many components.

### ISSUE THREAD

**Issue by horaceho** [xmartlabs/Eureka#155]
Instead of selecting hours and minutes, what's the proper way to setup `CountDownInlineRow` to select minutes and seconds?

**Comment by mtnbarreto** [comment]
There is no a easy way to accomplish this using Eureka build in rows.

To support this functionality we will have to add a new row that supports more than one picker view component since `PickerInlineRow` supports only one.

In your particular case, we can solve it having 2 components (mins and seconds). 

Let's think a little bit more about it, i don't have any elegant solution in mind right now.

**Comment by mikaoj** [comment]
I have done this in a project, and it isn't awfully hard to accomplish.

The only real problem was value having to be an Equatable collection and a Set wouldn't do because of the order being relevant (first value, first component, etc) and that you could select the same value in both components 1 and 1 in this case (being 1 second and 1 minute). And Array doesn't officially implement the Equatable protocol.

Swift 3 will will probably have Arrays implement Equatable for Equatable objects (can't find where they sad so right now), but for now I solved it by wrapping Array in an EquatableArray (https://github.com/mikaoj/EquatableArray) :)

**Comment by hardikdevios** [comment]
+1 need solution for this

**Comment by eflyjason** [comment]
+1

**Comment by supergithuber** [comment]
I fork the master branch and realize the feature with TwoComponentsPickerRow and TwoComponentsPickerInlineRow.
You can see a demo in https://github.com/supergithuber/Eureka

**Comment by karsonbraaten** [comment]
Any update on this?

**Comment by rburgul** [comment]
Likewise I have some deep hierarchical menus and need dual pickers for strings. Would really value help here.

**Comment by mtnbarreto** [comment]
`DoublePickerInlineRow`, `DoublePickerRow`, `DoublePickerInputRow` rows provide this functionality. 
It will be released in the next Eureka version (current 4.1.1), for now use master branch.
