### ISSUE TITLE
ComboBoxRow

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#162]
I would really love to see a ComboBoxRow.  i.e.  TextRow with List below.  I suppose there may also be a way to do this with a TextRow, a List and a predicate.  Anyone have some example code?

**Comment by rlaferla** [comment]
Is there a way to have the predicate evaluated every time the user types a character instead of when they press Enter?

**Comment by mtnbarreto** [comment]
I would suggest you to create a brand new custom row rather than using TextRow. 

If you go for this solution you can just add a target action to its textField view like:
```swift
textField.addTarget(self, action: "textFieldDidChange:", forControlEvents: .EditingChanged)
```
then filter the list using the predicate from within `textFieldDidChange` method.

If you still prefer to use TextRow, any change of a row value is notified through onChange callback as the readme points out here: https://github.com/xmartlabs/Eureka#customization

**Comment by rlaferla** [comment]
Thanks.  I've trying it out now.
