### ISSUE TITLE
Feature request: TokenRow

### ISSUE THREAD

**Issue by rlaferla** [xmartlabs/Eureka#165]
It would be nice to have a token field row like NSTokenFieldCell or venmo/VENTokenField.

**Comment by mtnbarreto** [comment]
If you have time to implement it i'm willing to reference your implementation from the eureka readme or merge it into the Example project (we have a swift [file](https://github.com/xmartlabs/Eureka/blob/master/Example/Example/CustomCells.swift) that has many custom rows). 

I think that provide it by default (along with the other native rows) is not good idea since no one have asked for it before and there is no a unique implementation for it (we can show the token options in many different ways). 

Regards

**Comment by mtnbarreto** [comment]
We've created [EurekaCommunity](https://github.com/EurekaCommunity) github organization that is intended to be a catalog for Eureka plug-ins such us custom rows, themes, etc. 

We would love to add your token row there, if you have already implemented it we can help you to publish the control and also give write permissions over the organization/repository.

Awaiting your response....

**Comment by mats-claassen** [comment]
A [TokenRow](https://github.com/EurekaCommunity/TokenRow) has been implemented in EurekaCommunity. Feel free to use, contribute and share.
