### ISSUE TITLE
DecimalRow formatter wrong for too-big number?

### ISSUE THREAD

**Issue by eflyjason** [xmartlabs/Eureka#194]
So when I use `DecimalRow()` and type for example `3000000000000000000` (`3e+18`):

![img_8442](https://cloud.githubusercontent.com/assets/4939421/12416363/0ee6f042-bedc-11e5-9b7a-04245980c889.PNG)

It return `2,999,999,884,200,770,000.00`:

![img_8443](https://cloud.githubusercontent.com/assets/4939421/12416370/1519d5c4-bedc-11e5-945c-91bbbdb3d737.PNG)

So how can I fix it? Thanks!

**Comment by fantasticfears** [comment]
`DecimalRow` relies on the `Float` which only has a precision of 7 digits approximately. Define another DecimalRow based on Double could help.

----

Here I want to argues some naming strategy and design.

I don't understand why Float is used. Since Double seems always better as Swift book described.
As for `DecimalRow`, it is super hard to find out it's based on Float by looking this name. Is `Decimal` equals `Float`? I believe the answer is NO.
Why this naming is critical? Swift will consider type cast from a float to double as a failure which gives an unexpected `nil`.

**Comment by mtnbarreto** [comment]
@fantasticfears 
Considering the precision issue i would also prefer to switch to `Double`. I just realized about this terrible Float precision.
I think that changing the DecimalRow type to Double will fix the issue. Define another row could introduce misunderstandings. 
At the same time there may be eureka users relying on this Float value and their code will no longer compile until they update it. It seems a simple issue that anyone can easily fix if we properly document the  DecimalRow change.

Regarding DecimalRow name, it comes from decimal numbers and not NSDecimalNumber or any obj-c, swift type. 

@fantasticfears Do you want to make the `DecimalRow` changes?

**Comment by fantasticfears** [comment]
> At the same time there may be eureka users relying on this Float value and their code will no longer compile until they update it. It seems a simple issue that anyone can easily fix if we properly document the DecimalRow change.
It's a break change. Unfortunately it may not break complication. It depends on how the user want to use it. For example, I use type cast because of `values:` function which will just give me an nil. But making change from `Float` to `Double` is worth it.

I'm sorry I can't help you with PR. I'm rushing on a demo :(

BTW: Downcast `as` is really misleading when it comes to basic type in Swift.
