### ISSUE TITLE
Propose to make cursor starting from the right end of current text for TextRow

### ISSUE THREAD

**Issue by Yannmm** [xmartlabs/Eureka#2044]
Just noticed when tap blank area of a TextRow to edit, the cursor will start blinking at the left end of already-entered text. That can cause trouble to users, considering it's not easy to move cursor on a mobile device by dragging.

I think this is due to the nature of UITextField. It's natural when the text is left-aligned, as most of Apple apps use it that way. But Eureka uses right-aligned text field.

One solution is to make cursor appear at the right end by default when clicking blank area. If click on text, then follow the original behavior.

![2020-05-29 16 57 11](https://user-images.githubusercontent.com/13806962/83241565-96e24400-a1cd-11ea-9593-64738b0c30ce.gif)

**Comment by mats-claassen** [comment]
Good point. Actually when tapping outside of the text field the cursor position will be put at the end. However, currently the textfield occupies most of the blank space. Tapping that blank space moves the cursor to the closest position, which is the front.

Fixed in the linked PR by changing the hugging priority of the text field.
