### ISSUE TITLE
Crash on ipadOS/iOS 15 when pressing Tab key using hardware keyboard

### ISSUE THREAD

**Issue by jurex** [xmartlabs/Eureka#2181]
Reproducible crash on ipadOS/iOS 15 when pressing Tab key multiple times using hardware keyboard (bluetooth, or usb-c)

Environment: iPad Pro 11, iPad OS 15.0.0, Eureka 5.3.3

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Received a call to becomeFirstResponder while processing a focus update, which is not supported.'
terminating with uncaught exception of type NSException
```

in Core.swift:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/925257/136262844-91cb19e7-c40b-434c-944c-ec6605769757.png">

Could be related to the new iOS 15 focus system, or something similar...

**Comment by qizdyyt** [comment]
I can avoid this issue by using UIScrollView.keyboardDismissMode.

**Comment by trackvia-ios** [comment]
Bumping and confirming we are seeing this in our latest environment: iOS 15.2, iPad Pro 12.9 5th gen simulator, Eureka 5.3.3

libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Received a call to becomeFirstResponder while processing a focus update, which is not supported.'

**Comment by mats-claassen** [comment]
Hey @trackvia-ios, @jurex, @dreymonde the PR linked above should fix the issue. Sorry for the late fix.
Please report if you still see any related crashes
