### ISSUE TITLE
MultipleSelectorRows not accepting value as array when using setValues()

### ISSUE THREAD

**Issue by Tramvai** [xmartlabs/Eureka#239]
Trying to add an array of values to MultipleSelectorRows using the setValues() method and a tag-value dictionary does not work.

My MultipleSelectorRows have a type of String. When I add a value to it in the initialize method (`$0.value = ["blah"]`), it works as intended. However when I try to add a value to it later in the code, the value stays as nil.

```
var values = form.values()
values["MultipleSelectorRow"] = ["blah"]
form.setValues(values)
tableView?.reloadData()
(form.rowByTag("MultipleSelectorRow") as! MultipleSelectorRow<String>).value // Will be nil
```

**--- EDIT:**
Turning the array into a Set worked. Is this intended behaviour, considering using the array worked in the initializer method?
`Set(["blah"])`

**Comment by mtnbarreto** [comment]
@Tramvai This is the MultipleSelectorRow base class definition:

```swift
/// Generic options selector row that allows multiple selection.
public class GenericMultipleSelectorRow<T: Hashable, VCType: TypedRowControllerType 
where VCType: UIViewController,  VCType.RowValue == Set<T>>: 
Row<Set<T>, PushSelectorCell<Set<T>>>, PresenterRowType {
```

Notice the `Set<T>` which is the row type of MultipleSelectorRow<T>.

MultipleSelector `options` is an Array to display the option in the same order it appears in the array.
MultipleSelector `value` is a set since it doesn't matters the selection order.
