### ISSUE TITLE
Custom cell with array cell type

### ISSUE THREAD

**Issue by Hendra-Huang** [xmartlabs/Eureka#263]
For example i have data like this:
`{"Large": 10, "Medium": 5, "Small": 7}`
and i wanted to display the data like a chart. So I created custom cell to display the chart. I tried to create custom cell with array cell type, but it is not working. The error says that my array does not conform to protocol Equatable. So is there any solution so i can pass my data in array type to a eureka cell ?

**Comment by mtnbarreto** [comment]
@Hendra-Huang Any type used by a Eureka row must be Equatable, it's a library constraint and it's needed to know when a value is changed.
 
According [swift evolution](https://github.com/apple/swift-evolution/blob/e06662c2049c223dc226bcf5de50db44d61e8ca2/README.md) in swift 3 Array<T:Equatable> will be Equatable by definition.

*Complete generics: Generics are used pervasively in a number of Swift libraries, especially the standard library. However, there are a number of generics features the standard library requires to fully realize its vision, including recursive protocol constraints, the ability to make a constrained extension conform to a new protocol (i.e., an array of Equatable elements is Equatable), and so on. Swift 3.0 should provide those generics features needed by the standard library, because they affect the standard library's ABI.*

Until then you can wrap the Array into a custom type and make this custom type conform to `Equatable`.

Does it make any sense for you?

**Comment by Hendra-Huang** [comment]
@mtnbarreto Okay thanks. I have tried a workaround by using NSMutableArray for custom row value and it works
