### ISSUE TITLE
Decimal localization wrong 

### ISSUE THREAD

**Issue by MHX792** [xmartlabs/Eureka#264]
My localization has a "," as a seperator instead of "." – when not editing the decimal number the seperator shows up correctly as ",". During editing it switches to ".". 

BTW: After pressing the seperator on the keypad it automatically adds a "0", which I don't want. I would like the user to specify the first number after the seperator.

Xcode: 7.2.1
iOS: 8.1

**Comment by mtnbarreto** [comment]
@MHX792 
Are you using formatters?  `row.formatter = .....`

**Comment by MHX792** [comment]
Nope, where can I find a documentation about `row.formatter`?

**Comment by mtnbarreto** [comment]
no documentation yet. :) I will improve add how to use it in the readme shortly. 

Actually I think this is not an issue. You probably should use formatters to get this behaviour. 
Maybe Eureka should have this behaviour (correct formatter and useFormatterDuringInput = true) by default.

Let me think a little bit about it.

**Comment by mtnbarreto** [comment]
@MHX792 See #267 . 

You can either or remove the formatter or set up the DecimalRow as...

```swift
<<< DecimalRow() {
                   $0.title = "DecimalRow"	
                   $0.value = 5
                   $0.formatter = DecimalFormatter()
                   $0.useFormatterDuringInput = true
        }
```

**Comment by MHX792** [comment]
Thanks, but seems like the `DecimalFormatter` class is not in the latest pod version of Eureka. I copied it from here: https://github.com/xmartlabs/Eureka/blob/master/Source/Rows.swift
I am little bit confused, though. With your code above, the zeros don't get deleted when I tap on backspace (all numbers change to zeros, when deleted). 
I am kind of confused. What I want is the standard `UITextField` behaviour for entering numbers with the decimal pad. How to accomplish that?

**Comment by mtnbarreto** [comment]
Regarding the extra 0 at the end. No matter if the entered value has decimal digits or not the formatter will add zeros in order to have at least minimumFractionDigits fraction digit. 

When `useFormatterDuringInput` is false, the formatter is applied each time the first responder is resigned from the textField. 

When `useFormatterDuringInput` is true, formatter is used always, this means even when the text is being edited. 
When editing we can tap on a digit but the formatter adds more than one character, this is what's happening when a thousand separator appears, and in this case we need to fix the cursor position through `FromatterProtocol` conformance. 

It's up to you to conform to `FromatterProtocol` as well as to use formatters during editing. 

Regarding the the empty value, it's also up to you to implement the formatter so you can do something like this: 

```swift
override func getObjectValue(obj: AutoreleasingUnsafeMutablePointer<AnyObject?>, forString string: String, errorDescription error: AutoreleasingUnsafeMutablePointer<NSString?>) -> Bool {
        guard obj != nil else { return false }
        let str = string.componentsSeparatedByCharactersInSet(NSCharacterSet.decimalDigitCharacterSet().invertedSet).joinWithSeparator("")
        obj.memory = str == "0\(self.decimalSeparator)00" ? nil : NSNumber(integer: Int(str) ?? 0)
        return true
    }
```

This was the only the maintainers team found to make it generic and extensible.
