### ISSUE TITLE
Long Placeholder for TextAreaRow goes outside of cell

### ISSUE THREAD

**Issue by jbejar** [xmartlabs/Eureka#287]
![image](https://cloud.githubusercontent.com/assets/3386245/13325402/e4ba8c9a-db9e-11e5-8443-810e31cb93fa.png)

**Comment by jbejar** [comment]
So I was able to fix it by accessing the placeHolder label and setting the number of lines. Should this be in the code though by default?
`        textArea = TextAreaRow {
            $0.value = originalValue
            $0.placeholder = control.placeholder
            $0.cell.placeholderLabel.numberOfLines = 4
        }`

**Comment by mtnbarreto** [comment]
@jbejar  It's an edge case scenario, normally the placeholder fits on the cell area. 

We don't add vertical height constraint to placeholder label because we want the text to appear at the top left corner. What you did is a good workaround solution.
I'm open to an alternative solution but it should not change the numberOfLines. Currently the value is 0, it seems to me the most appropriate value by default.
