### ISSUE TITLE
KeyboardReturnType

### ISSUE THREAD

**Issue by MPiccinato** [xmartlabs/Eureka#291]
I am attempting to set the .keyboardReturnType on a PasswordRow.

Since the value of .keyboardReturnType is nil I figured I would attempt to set it to a new KeyboardReturnTypeConfiguration struct. Swift is however throwing an error that it cannot be constructed.

I couldn't find any documentation changing the return key type on a particular form or particular row.

**Comment by mtnbarreto** [comment]
Actually KeyboardReturnTypeConfiguration cannot be initialised from another module due to this:

"Default Memberwise Initializers for Structure Types The default memberwise initializer for a structure type is considered private if any of the structure’s stored properties are private. Otherwise, the initializer has an access level of internal.

As with the default initializer above, if you want a public structure type to be initializable with a memberwise initializer when used in another module, you must provide a public memberwise initializer yourself as part of the type’s definition."

-----------------------------------------------------------------------------------------------

I'm gonna make public the initializers and also update the readme. 

After my changes you should be able to use it like this ......

```swift
             <<< PasswordRow() {
                        $0.title = "PasswordRow"
                        $0.value = "password"
                        $0.keyboardReturnType = KeyboardReturnTypeConfiguration(nextKeyboardType: .Done, defaultKeyboardType: .Go)
                    }
```
