### ISSUE TITLE
Unnecessary abstraction in _XRow and XRow classes?

### ISSUE THREAD

**Issue by SpacyRicochet** [xmartlabs/Eureka#31]
I'm confused on why there is a extra layer of abstraction between the _actual_ Row classes and their `final` versions. For example:

```
public class _DateInlineRow: _DateInlineFieldRow, InlineRowType {
    
    public typealias InlineRow = DatePickerRow
    
    public required init(tag: String?) {
        super.init(tag: tag)
        dateFormatter = NSDateFormatter()
        dateFormatter?.timeStyle = .NoStyle
        dateFormatter?.dateStyle = .MediumStyle
        dateFormatter?.locale = .currentLocale()
    }
    
    public override func customDidSelect() {
        toggleInlineRow()
    }
}
```

```
public final class DateInlineRow: _DateInlineRow, RowType {
    required public init(tag: String?) {
        super.init(tag: tag)
        onShowInlineRow { cell, row, _ in
            let color = cell.detailTextLabel?.textColor
            row.onHideInlineRow { cell, _, _ in
                cell.detailTextLabel?.textColor = color
            }
            cell.detailTextLabel?.textColor = cell.tintColor
        }
    }
}
```

It seems to me that having `_DateInlineRow` is superfluous to `DateInlineRow`, **especially** since the `DateInlineRow` overrides the initialiser with something that apparently could have been put in `_DateInlineRow` instead. 

And most of the other version are just variations of;

```
public final class xRow : _xRow, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
    }
}
```

… where the override of the initialiser could have been omitted. 

Just wondering what the rationale is.

**Comment by mtnbarreto** [comment]
@SpacyRicochet  great question!

Basically the `final` modifier is needed to automatically inject the implementation of `RowType` protocol `initialiser`. This implementation is provided through `RowType` protocol extension. 

Swift doesn't allow us to add a `required` nor `convenience` modifier to a protocol `init` declaration neither to a protocol extension implementation so I ended up adding the `final` modifier to each row getting implicitly this initialiser.

If we delete the `final` modifier we are forced to override the initializer adding the required modifier to ensure that any subclass implements the initialiser. 

As you can see below implementing the initialiser is prone to error. What we're trying to do using the `final` modifier is preventing any programmer error in the initializer implementation.

```swift
// the propose of the initialiser is make the code more readable. 
public protocol RowType : TypedRowType {
    init(_ tag: String?, _ initializer: (Self -> ()))
}

extension RowType where Self: BaseRow, Cell : TypedCellType, Cell.Value == Value {
    
    public init(_ tag: String? = nil, _ initializer: (Self -> ()) = { _ in }) {
        self.init(tag: tag)
        let callback : Self -> () = RowDefaults.sharedInstance.defaultRowInitializer(self.dynamicType) as! Self -> ()
        callback(self)
        initializer(self)
    }
}
```

The extra layer you noticed on each row is because someone may need to extend a row and all rows are final by definition so we ended up adding this extra abstraction layer which can be extended.

So whenever someone wants to extend a row it should extend the `_<RowName>` superclass and conform to `RowType` getting implicitly the initialiser shown above and many more helpers.

Finally as you may have noticed we avoided to override the initialiser in order to show how to create a custom row. There is no difference (in terms of row definition/creation process) between Eureka rows provided by default and custom rows.

Let me know if i made it clear.
If you have another solution i'm willing to implement it.

**Comment by phiberjenz** [comment]
@mtnbarreto This should be somewhere in custom rows section in the readme. I can work on a PR if that's something that you would like there.
