### ISSUE TITLE
TextFloatLabelCell with textarea and multiple rows

### ISSUE THREAD

**Issue by sagits** [xmartlabs/Eureka#314]
Hi, i was trying to implement a TextFloatLabelCell that acts as an TextArea. The problem is that i need to conform _FloatLabelCell to TextView instead of TextField. Can someone help me please? Thanks in advance.

**Comment by mtnbarreto** [comment]
We have a lot of documentation about how to create custom rows such as blogposts (https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/, https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/) and repository [readme](https://github.com/xmartlabs/Eureka#custom-rows). 
Every Eureka build-in row is like a custom row so you can take a look at the native rows as well as Example project rows.
Also [EurekaCommunity](https://github.com/EurekaCommunity) github organization provides several complex custom rows that might be helpful to create a custom row from scratch.

I'm sending these information because its impossible for us to maintain the project, implement new features and help everyone to create its custom row. Hope you understand us.

I recommend you to answer that on stack overflow as contribution guidelines points out.
