### ISSUE TITLE
On DateInlineRow, cell.textLabel.textColor doesn't change on .onExpandInlineRow and .onCollapseInlineRow

### ISSUE THREAD

**Issue by allanrvj** [xmartlabs/Eureka#321]
Was trying to imitate the Reminder app wherein when you select the Alarm cell (under "Remind me on a day" cell), the detailTextLabel disappears, and the textLabel changes text and color. The detailTextLabel is successfully hidden, but the changing of colors don't work. So instead of writing this:

`.onExpandInlineRow{ cell, row, _ in`
`	cell.textLabel?.textColor = cell.tintColor`
`	cell.detailTextLabel?.hidden = true`
`	row.updateCell()`
`}`
`.onCollapseInlineRow {cell , row, _ in`
`	cell.textLabel?.textColor = UIColor.blackColor()`
`	cell.detailTextLabel?.hidden = false`
`	row.updateCell()`
`}`

I had to write this:

`.onExpandInlineRow{ cell, row, _ in`
`	row.cellUpdate({ (cell, row) -> () in`
`		cell.textLabel?.textColor = cell.tintColor`
`	})`
`	cell.detailTextLabel?.hidden = true`
`	row.updateCell()`
`}`
`.onCollapseInlineRow {cell , row, _ in`
`	row.cellUpdate({ (cell, row) -> () in`
`		cell.textLabel?.textColor = UIColor.blackColor()`
`	})`
`	cell.detailTextLabel?.hidden = false`
`	row.updateCell()`
}
`
Take note that I had to invoke row's cellUpdate method.

I don't know if it's a bug or just the way things work. I still love Eureka, though. :)

**Comment by mtnbarreto** [comment]
@allanrvj 
To make the first approach work you should remove `row.updateCell()` because it forces the row to be updated/refreshed overriding your previous change (`cell.textLabel?.textColor = cell.tintColor`).
The refresh implementation of a row, among other things, invokes  Cell `update()` function that updates the textLabel color as shown below...

```swift
    public override func update(){
        super.update()
        textLabel?.text = row.title
        textLabel?.textColor = row.isDisabled ? .grayColor() : .blackColor()
        detailTextLabel?.text = row.displayValueFor?(row.value)
    }
```

`cell.detailTextLabel?.hidden = true` works as expected since Cell `update()` doesn't update detailTextLabel hidden value. 

If you need to update the row as you said, you should go for the second approach. In fact I would recommend the second approach even when you don't need to update the row since Cell `update` invocation can occur at anytime by Eureka framework.

Ideally you should also move `cell.detailTextLabel?.hidden = true/false` to inside `cellUpdate` callback.

Regards
