### ISSUE TITLE
How to prevent cell from resigning first responder on using section.reload

### ISSUE THREAD

**Issue by rajeshmani27** [xmartlabs/Eureka#335]
Hi,

I am using Eureka ver 1.4.1 section.reload as a mechanism to refresh the section footer for remaining character count while the textfield is being updated.

However, the textfield resigns first responder upon section refresh and I have to explicitly click back on the screen to continue editing. I wanted to check if there is a way to avoid that. 

Also, is there a different way to update section footer without a section refresh as I see a small flicker from the data refresh on the Simulator.

Thanks in advance.

**Comment by rajeshmani27** [comment]
Update:
I use row.cell.cellBecomeFirstResponder(Direction.Down) within row.onChange method..as a workaround to restore the cursor on the UITextField within the TextRow after the Section footer's remaining character count message after every keystroke. However, I find this method makes the typing of the characters within the TextRow sluggish. Any alternative solution that just changes the section footer without section refresh would be helpful

**Comment by mtnbarreto** [comment]
The alternatives depends on how much are these changes on the header/footer view.....

`row.cell.cellBecomeFirstResponder(Direction.Down)` can be used from any point of your code. 
For instance we can invoke it after invoking section.reload(). `section.reload()` resigns section first responder so you have to put it back. 

```swift
section.reload()
// get first responder row
let row = ....
row.cell.cellBecomeFirstResponder(Direction.Down)
```

Alternatively you can make changes directly on the section header/footer view (i don't recommend this approach).

```swift
if let footer = row.section?.footer?.viewForSection(row.section!, type: HeaderFooterType.Footer, controller: self!) as? OnboardingTableFooterView {
      footer.titleLabel.text = "aaaaa"
      footer.titleLabel.textColor = .orangeColor()
      footer.backgroundColor = .clearColor()
}
```

I don't recommend the latter approach because whenever the section header/footer appears on the screen `public var onSetupView: ((view: ViewType, section: Section, form: FormViewController) -> ())?` is invoked overriding the changes you made directly on the view. 

`viewForSection(section: Section, type: HeaderFooterType, controller: FormViewController) -> UIView?` implementation invokes `public var onSetupView: ((view: ViewType, section: Section, form: FormViewController) -> ())?` so ideally you should implement all header/footer set up variants within `onSetupView` block or at least make sure `onSetupView` set up matches the changes made directly on the view. 


Let me know if this helps you out with your issue.

---------------------------------------------------------------------------------------

I think next alternative is not your case but just for clarification...
You can also display a completely different header/footer view (i mean a different view type) by setting up Section  `public var header: HeaderFooterViewRepresentable?` property using `public struct HeaderFooterView<ViewType: UIView> : StringLiteralConvertible, HeaderFooterViewRepresentable` type. `section.reload()` is needed to refresh the section header/footer in this case as well. 

Section header/footer documentation: https://github.com/xmartlabs/Eureka#section-header-and-footer

**Comment by dilizarov** [comment]
I'm unable to follow your "not recommended alternate example" as OnboardingTableFooterView isn't a thing. Any updates? @mtnbarreto

**Comment by dilizarov** [comment]
This is how I achieved it:

```
row.section!.footer = HeaderFooterView(title: footerText)
self.tableView?.footerView(forSection: 2)?.textLabel?.text = footerText
self.tableView?.footerView(forSection: 2)?.sizeToFit()
```

Replace the footer to take effect when section gets re-setup. Immediate changes will be visable from changing the footerView directly.
