### ISSUE TITLE
How to include LocationRow in own project?

### ISSUE THREAD

**Issue by Opelor** [xmartlabs/Eureka#338]
Can someone guide me on how to setup the LocationRow code in my project code.

I've tried a couple of things with no success.

Thanks.

Eureka, '~> 1.4.1’
iOS Deployment Target, 9.2
Xcode, 7.2

**Comment by mtnbarreto** [comment]
@Opelor `LocationRow` is not provided within eureka framework because it requires MapKit framework to work and in case the app doesn't make use of LocationRow or MapKit we are adding a unnecessary framework dependency.

For now you can copy LocationRow implementation to your app project. We have plans to provide custom rows as cocoapods subspecs sometime...
