### ISSUE TITLE
Can you dynamically create a form?

### ISSUE THREAD

**Issue by otherjohn** [xmartlabs/Eureka#341]
Would it be possible with the current version to take a json file and basicly use it to dynamicaly create the form?

**Comment by mtnbarreto** [comment]
It's completely possible but this is not a build-in feature so you would have to do the following tasks...
* Define a XML scheme to represent a form.
* Implement a method that receive the xml as a parameter and returns a Form. *It would be helpful to use s json parser library to make sure the xml conforms to the scheme and also to make easier the method implementation since you will work with strong typed values instead of AnyObject.*

**Comment by dneykov** [comment]
Can anyone show an example of this?
I'm trying to create form from fields coming from API request.

**Comment by plastus** [comment]
Take a look at the "initializeForm()" function in the Eureka example. From here, you can start designing the form and then if you need to determine what kind of row to insert you can put in your logic there to read in from JSON/XML API return payload. When you want to add to the initialized form use "form.last!"

e.g. form.last! <<< NameRow(.......)

**Comment by dneykov** [comment]
Thanks for your reply.
I did it in exact same way.

**Comment by fusionbeam** [comment]
hi. how did it go with initializing a form from a json schema?
