### ISSUE TITLE
How to reuse custom cell?

### ISSUE THREAD

**Issue by marshallYin** [xmartlabs/Eureka#350]

**Comment by mtnbarreto** [comment]
@marshallYin  good question..
Currently Eureka does not reuse cells, each row has its correspond cell. This is a architecture decision that comes from XLForm project (eureka obj-c "version").
The reason of not reusing the cells is keeping the changes made on a row's cell, specially those changes that are set up during row creation time or within onCellSetup callback.

This should not be a performance problem when creating forms using Eureka since normally table view forms have just a few cells.

Regards

**Comment by marshallYin** [comment]
Thanks for your reply.
