### ISSUE TITLE
iPhone 5c crashed when I set "cell.height" by cellUpdate

### ISSUE THREAD

**Issue by ghysrc** [xmartlabs/Eureka#358]
I want to set height to several rows, so I add the "cellUpdate" method to these rows.
`.cellUpdate({ (cell, row) in
       cell.height = 50
})`
It works fine on iPhone 6 and iPhone 5s. It only crashes on iPhone 5c. And only the height property.
I also tried the "defaultCellUpdate", it crashes too.

**Comment by mtnbarreto** [comment]
try using `cell.height = { 50 }`

This is the definition of `BaseCell`'s height property:

```swift
    /// Block that returns the height for this cell.
    public var height: (()->CGFloat)?
``` 

Regards

**Comment by mtnbarreto** [comment]
BTW, I think the cell height should be set up before `cellForRowAtIndexPath` (which internally calls cellUpdate callback) is invoked because this height will be returned as the height value of `heightForRowAtIndexPath`.

Order of invocations: 
1. heightForRowAtIndexPath --> cell.height callback
2. cellForRowAtIndexPath --> cellUpdate callback

**Comment by ghysrc** [comment]
Thanks. I just start using Eureka, this is a great library.
