### ISSUE TITLE
Cannot change color to the textlabel for a cell of type SwitchRow

### ISSUE THREAD

**Issue by SamBellerose** [xmartlabs/Eureka#359]
The default color is black, is there a way to modify this color ?

I tried 

`textLabel?.textColor = UIColor().whiteColor()`

But it's not working. Am I using the right function ?

Thanks !

**Comment by mtnbarreto** [comment]
pretty similar to #161. 
You should set up it form within `cellUpdate` callback  since each time the cell is displayed Eureka sets up its color depending on its row disabled property value.

For additional info take a look at the issues labeled with [callback: cellUpdate](https://github.com/xmartlabs/Eureka/issues?q=label%3A%22callback%3A+cellUpdate%22) 

Regards
