### ISSUE TITLE
navigationOptions = .None not working

### ISSUE THREAD

**Issue by gmertk** [xmartlabs/Eureka#36]
Hi, 

You can also see this in "Accessory View Navigation" of the example project. When I switched off navigation accessory view, I still get the navigation view as seen in the screenshot below.

![simulator screen shot 15 oct 2015 14 32 51](https://cloud.githubusercontent.com/assets/907281/10512516/ba0c38d0-7349-11e5-9b30-a7252f49784a.png)

I expected to have no view above the keyboard when I set navigationOptions to None.

**Comment by mtnbarreto** [comment]
@gmertk 
It seems that Swift static analyzer and compiler get confused when we use the reduced syntax` .None` instead of `RowNavigationOptions.None`.

I think swift error is due to `navigationOptions` property is a OptionalType and optional is internally represented as .None (take a look optional definition below):

```swift
public enum Optional<Wrapped> : _Reflectable, NilLiteralConvertible {
    case None
    case Some(Wrapped)
...
```
I will rename .None to .Disabled to avoid the error. 
Thanks for reporting the issue!

**Comment by gmertk** [comment]
Thanks for the quick fix @mtnbarreto I would appreciate if you can push a new release on cocoapods

**Comment by mtnbarreto** [comment]
done!
