### ISSUE TITLE
LabelRow not preserving value change after scrolling.

### ISSUE THREAD

**Issue by allanrojas** [xmartlabs/Eureka#384]
So I downloaded the example and it seems the LabelRow is not functioning correctly; it says "tap the row" and if you do, it adds a flag to the text, but if you scroll down and then back up, the value is not preserved.

Any ideas?

**Comment by mats-claassen** [comment]
Yeah this is just an example. 
LabelRow does not actually add flags, its a row where you put a static text in both `taxtLabel` and `detailTextLabel`. Here the value of the second one is changed on each tap but resetted when the cell reappears on screen

**Comment by mtnbarreto** [comment]
`titleTextLabel` is set up each time cell appears on screen like. To preserve it you should make the changes on row abstraction properties instead of cell properties.  This is because each time cells appears on screen the cell is updated based on its row information. 

In this particular case the cell titleTextLabel text is set up with row.title. Since we are updating directly the titleTextLabel from `onCellSelection` callback, this change is not preserved when the table view cell is scrolled out of the screen.

Basically the cell refresh/update process involves these invocations:

---> `tableView(tableView, willDisplayCell, forRowAtIndexPath )`
--------------> `row.updateCell()`
-----------------------------> `cell.update()`
-----------------------------> `defaultCellUpdate` callback
-----------------------------> `cellUpdate` callback

The proper code to update `titleTextlabel` is:
 
```swift
                <<< LabelRow () {
                        $0.title = "LabelRow"
                        $0.value = "tap the row"
                    }
                    .onCellSelection { cell, row in
                        row.title = (row.title ?? "") + " 🇺🇾 "
                        row.reload() // or row.updateCell()
                    }
```

Hope this clarify something!

> I'm gonna update the example to avoid any confusion.
