### ISSUE TITLE
DateTimeInlineRow returned value

### ISSUE THREAD

**Issue by dneykov** [xmartlabs/Eureka#394]
Hi everyone, this is great library.
I have one question about DateTimeInlineRow. Is it possible the returned value(date) to be in local time zone.
For example if I choose 2016-04-27 14:05:54 from the date picker, returned value is 2016-04-27 11:05:54 +000.
Is it possible to get only 2016-04-27 14:05:54 direct from the picker without further converting.

**Comment by mtnbarreto** [comment]
Is your timezone UTC + 03?

**Comment by dneykov** [comment]
Yes

**Comment by mtnbarreto** [comment]
The date seems to me okay. `debugDescription` of NSDate returns gmt time and based on this is your responsibility to show the time using the proper date formatter which has its own timezone.

**Comment by dneykov** [comment]
The date is okay but I'm loading the fields dynamically from API and when submitting the form I serialize all the fields and sending to the server.
The problem is that when I send the date and time they are 3 hours off.
Is there function to get all dateRows so I can loop through them?
As I said they are dynamic fields and the tags are different so I can't do it static.
Any suggestions will be welcome. 
Thanks.

**Comment by mtnbarreto** [comment]
This is a serialization problem, nothing to do with Eureka.  

`row.value` provides you with a NSDate which the right value.  Why not store this time as UTC+00 instead of having all these days in a different timezone information or +03? Doing that all your times will be relative with each other and are easy to shown regardless of app user location that may change (summer time, travels, etc).

Usually json serialization process convert the app date from device timezone (locale) to UTC+00 but you can change this to UTC+03 that does not make any sense specially if you can change the backend REST API.


If you still want to store UTC+03 you will have to convert any app user time to +03 time before sending it to server. 
```
let formatter = NSDateFormatter()
formatter.locale = // set up you +03 time zone
let jsonString = formatter.stringFromDate(val)
```

Notice that by default almost Json parsers/serializers works using ISO 8601 date string format. This library may be useful to work with dates ... https://github.com/malcommac/SwiftDate

**Comment by murraycollingwood** [comment]
I'm tending to agree with Daniel, my server is UTC+10 and my app could be anywhere in the world.  The customer might be setting a DateRow that is relative to their current location, that isn't a problem, but if they are wanting to set a DateRow that is relative to the server time, then I won't know how to convert this unless I know the users original timezone.  
If you were to simply pass back the DateRow in the users current locale I can then apply the timezone or not depending on whether the value is considered relative to the location or the server.

One alternative is that I set the timezone for the DateRow, so if I need a server date/time I can set a row parameter to apply the server timezone.  The value can then be transferred as UTC+0 (the current process), however the app will then display/select the date/time using UTC+10 (my server timezone).
