### ISSUE TITLE
Impossible to set the Keyboard Return Key Type

### ISSUE THREAD

**Issue by Grmiade** [xmartlabs/Eureka#407]
I have this form:

```swift
form +++ Section()
    <<< EmailRow("email"){
        $0.placeholder = "Email"
        $0.cell.textField.returnKeyType = .Next
        $0.cell.tintColor = FlatNavyBlueDark()
    }
    <<< PasswordRow("password") {
        $0.placeholder = "Password"
        $0.cell.textField.returnKeyType = .Done
        $0.cell.tintColor = FlatNavyBlueDark()
    }
```

But my returnKeyType setting don't work :/ It changes nothing.
When you have 2 rows which follow, this behavior should not be natively? (with `KeyboardReturnTypeConfiguration`)
The keyboard return key should be Next until the last possible row. Currently it don't work :/

**Comment by mtnbarreto** [comment]
Sorry for the little documentation. But the idea is simple....

If you want to set up the keyboardReturnType of a specific row, you can set up `cell.keyboardReturnType`. If this property is nil, Eureka uses `form.keyboardReturnType` otherwise `defaultKeyboardReturnType` static property indicates the keyboardReturnType.

As you can see there are many abstraction levels to customize it depending on the scope desired. 

> BTW use `cellUpdate` to set up cell properties such as `cell.tintColor = FlatNavyBlueDark()`, by doing it from within row init closure, the cell is being created at row init time and ideally the cells should be created when tableView dataSource provides them.

**Comment by Grmiade** [comment]
Thanks for the advice about `cellUpdate`.
But impossible to display the `.Next` keyboard return key on the first row.
My code:
```swift
override func viewDidLoad() {
        super.viewDidLoad()
        navigationOptions = .Disabled
        form.keyboardReturnType = nil
        
        form +++ Section()
            <<< EmailRow("email"){
                $0.placeholder = "Email"
            }.cellUpdate({
                (cell, _) in
                cell.tintColor = FlatNavyBlueDark()
            })
            <<< PasswordRow("password") {
                $0.placeholder = "Password"
            }.cellUpdate({
                (cell, _) in
                cell.tintColor = FlatNavyBlueDark()
            })
        
        form +++= ButtonRow() {
                $0.title = "Log in"
                $0.cell.tintColor = FlatNavyBlue()
            }.onCellSelection({
                (_, _) in
                self.logIn()
            })
    }
```

**Comment by mtnbarreto** [comment]
@Grmiade Which Eureka version are you using? 
I tested an example and it worked perfectly for me.

Does the second row enabled?

**Comment by mtnbarreto** [comment]
Delete this line `navigationOptions = .Disabled` and it will work. `navigationOptions` indicates how to navigates among rows and has nothing to do with navigation input accessory view. 

If you don't want to show the accessoryInputView but keep the row navigation behaviour you should  override `FormViewController` `navigationAccessoryView` method by making it return nil.

`navigationOptions = .Disabled` will hide the input accessory view since there is no navigation at all but at the same time keyboard return type will reflect this configuration.

For additional info take a look at https://github.com/xmartlabs/Eureka#how-to-change-the-bottom-navigation-accessory-view .

Hope it helps.

**Comment by Grmiade** [comment]
Indeed, when i remove this line, it's works.
But i didn't succeed to hidden the `accessoryInputView` through `navigationAccessoryView` method.
I can't simply return `nil`. Sorry i'm a beginner in iOS and swift.
Thanks so much for your help.

**Comment by mtnbarreto** [comment]
Sorry, i didn't explain it clearly. 

I will have to move `public func inputAccessoryViewForRow(row: BaseRow) -> UIView?` from `FormViewController` extension to the class itself because extension methods can not be overridden in swift yet. 

Then you will have to override it as shown below....

```swift
    override func inputAccessoryViewForRow(row: BaseRow) -> UIView? {
        return nil
    }
```
