### ISSUE TITLE
How to change the alignment of PushRow, DateTimeRow, and ActionSheetRow?

### ISSUE THREAD

**Issue by xinranw** [xmartlabs/Eureka#409]
I am looking to implement left alignment on the rows I mentioned above. Is that possible?

I looked at a similar issue from the XLForm repo ([link](https://github.com/xmartlabs/XLForm/issues/622)) but I couldn't find the same functionality in this library.

Thanks for any help!

**Comment by mtnbarreto** [comment]
There is no way because the cell we use in these rows is the default `UITableViewCell` which is provided by UIKit and according to this discussion http://stackoverflow.com/questions/3467288/center-align-text-in-uitableviewcell-problem we have to create the cell using `UITableViewCellStyle.Default` as its style to be able to customize the alignment otherwise the alignment is not reflected in the UI.

As an alternative, you can create your custom push row by extending to `_PushRow<..>` ...

```swift
public class _PushRow<T: Equatable, Cell: CellType where Cell: BaseCell, Cell: TypedCellType, Cell.Value == T> : SelectorRow<T, Cell, SelectorViewController<T>> {
    
    public required init(tag: String?) {
        super.init(tag: tag)
        presentationMode = .Show(controllerProvider: ControllerProvider.Callback { return SelectorViewController<T>(){ _ in } }, completionCallback: { vc in vc.navigationController?.popViewControllerAnimated(true) })
    }
}
```

Let me know if this works.

**Comment by ThinkBIG-Company** [comment]
Place this code anywhere in your project
/// A selector row where the user can pick an option from a pushed view controller
public final class __PushRow<T: Equatable> : _PushRow<PushSelectorCell<T>>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        
        cellStyle = .subtitle
    }
    
}

It works after hours of finding the answer

**Comment by wimzee-rcheng** [comment]
Sorry for reviving a dead thread but I ran into the same issue 4.5 years later, and a solution that worked for me is to update the cell style to default, and then overwrite the alignment and value in cellUpdate:
`
PushRow<String>() {
    $0.options = options
    $0.value = $0.options?.first
    $0.cellStyle = .default
}
.cellUpdate { cell, row in
    cell.textLabel?.text = row.value
    cell.textLabel?.textAlignment = .left
}

`
