### ISSUE TITLE
Problem casting BaseRow

### ISSUE THREAD

**Issue by Zigzag968** [xmartlabs/Eureka#463]
Hi,

I try to cast `BaseRow` so that i can call `onCellHighlight` / `onCellUnHighlight`, but the cast fails.

My goal is to configure `onCellHighlight` and `onCellUnHighlight` for all cells, in order to display/hide a tooltip on the row.

So i created a subclass of the `Section` type, so that i can override `rowsHaveBeenAdded` method and have a reference of each row of a section :

<img width="751" alt="capture d ecran 2016-05-30 a 11 47 57" src="https://cloud.githubusercontent.com/assets/411361/15646126/5dbdac14-265c-11e6-9e8b-528d15f2a019.png">

The app build without any problem, and any warnings on this block, but for example at runtime the cast of a `TextRow` to `R` fails.

Did i missed something ?
Thanks a lot
Alex

**Comment by mtnbarreto** [comment]
`onCellHighlight` is declared within `RowType`..

```swift
    /**
     Sets a block to be called when the cell corresponding to this row becomes first responder.
     
     - returns: this row
     */
    public func onCellHighlight(callback: (cell: Cell, row: Self)->()) -> Self {
        callbackOnCellHighlight = { [unowned self] in  callback(cell: self.cell, row: self) }
        return self
    }
```

Each row is a specific `RowType` and it's imposible to cast it from FormViewController that doesn't know the row dynamic type.

As a workaround you could use `defaultCellSetup` on each type. then set up the OnCellHighlight/onCellUnhighlight callback from within `defaultCellSetup` closure.

You should be able to implement a generic function and then call it with each type or add a method to `RowType` through protocol extension.


If you take a look at Eureka unit tests, in order to check that the callback works as expected, we declared a generic function...

```swift
    private func defaultCellSetupTest<Row where Row: BaseRow, Row: RowType,  Row: TypedRowType, Row.Value == Row.Cell.Value>(row:Row){
        var invoked = false
        Row.defaultCellSetup = { cell, row in
            invoked = true
        }
        formVC.form +++= row
        row.cell // load cell
        XCTAssertTrue(invoked)
    }
```

then we can call it using each row type.

```swift
        defaultCellSetupTest(TextRow())
        defaultCellSetupTest(IntRow())
        defaultCellSetupTest(DecimalRow())
        defaultCellSetupTest(URLRow())
        defaultCellSetupTest(DateRow())
        defaultCellSetupTest(DateInlineRow())
        defaultCellSetupTest(PopoverSelectorRow<String>())
        defaultCellSetupTest(PostalAddressRow())
        defaultCellSetupTest(SliderRow())
        defaultCellSetupTest(StepperRow())
```

> This approach allows you to write less code to set up the `defaultCellSetup` callback. The callback parameters are strongly typed and should be known at compilation time so there is no way to set up it to every row (at least from FormViewController class).
