### ISSUE TITLE
Large system preferred font + fixed font sizes causes strange row layouts

### ISSUE THREAD

**Issue by jpaas** [xmartlabs/Eureka#470]
If I use cellSetup to set a fixed font size on a cell element such textLabel, that is smaller than the system preferred font used, I get some strange row layouts. Typically the label will align to bottom of the cell rather than vertical center on cells such as SwitchRow, LabelRow, HeaderFooterView, or any of the SelectorRows.

- Environment: Eureka 1.6.0, Xcode 7.3.1, iOS 9.3.x

**Comment by mats-claassen** [comment]
Those rows use the UITableViewCell's textLabel so the layout of that label is a thing of iOS rather than Eureka. I tried what you said and it looks like the label is aligned to the bottom of the accessoryView.
![screen shot 2016-06-14 at 9 56 53 am](https://cloud.githubusercontent.com/assets/8573865/16043520/626affb2-3216-11e6-8943-1d8a51161848.png)
I dont think this is a Eureka bug. You should adjust the height of the cell or create a custom row for this.

**Comment by jpaas** [comment]
Ok thanks for following up on this
