### ISSUE TITLE
hidden doesnt work with "forward reference"

### ISSUE THREAD

**Issue by everlof** [xmartlabs/Eureka#493]
Eureka: 1.6
XCode: 7.3.1 (7D1014)
OS: OS X El Capitan, 10.11.4

When using `hidden` I cant refer to an element which will be defined after the current.

```swift
            <<< SwitchRow("req_a") {
                $0.title = "Requirement A"
                $0.value = false
                $0.hidden = .Predicate(NSPredicate(format: "$req_b == true"))
            }

            <<< SwitchRow("req_b") {
                $0.title = "Requrement B"
                $0.value = false
            }
```

Will give me:

```
2016-06-10 20:23:26.351 Grannsaker[61583:5074042] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Can't get value for 'req_b' in bindings {
}.'
```

**Comment by mats-claassen** [comment]
You are right. Using forward conditions with predicates will not work. You must use Condition.Function if you are going to create forward dependencies. Example:
```
$0.hidden = Condition.Function(["req_b"], { form in
                        return (form.rowByTag("req_b")?.baseValue as? Bool) == true
                    })
```

**Comment by everlof** [comment]
Thank you for the workaround. Is it an issue or is it just by design?

**Comment by mats-claassen** [comment]
I would not call it an issue, but it just does not work. :-)
In fact the Condition enum supports functions because the use of predicates is limited. Using predicates can make things a bit easier with shorter code but does not support all cases.

In this specific case what happens is that the `substitutionVariables` passed to the NSPredicate do not contain one of the required tags. We could implement a workaround to include nil values for some tags if they are referenced before being used but I think it is not necessary as `Condition.Function` works for this case and because it is not very common to use forward dependencies.

Do you agree with that?

**Comment by everlof** [comment]
I'm fine as long as there is a way to do it!

My thoughts are just that people coming from XLForms might expect it to
work with forward references? (I think I used that there..).

Anyway, thanks for the info! :)


2016-06-16 17:16 GMT+02:00 Mathias Claassen <notifications@github.com>:
