### ISSUE TITLE
PushRow with header and footer

### ISSUE THREAD

**Issue by biskit** [xmartlabs/Eureka#529]
is it possible?

**Comment by mats-claassen** [comment]
Sure it is. Just implement your own controller and change the presentationMode of `PushRow` to present your view controller.
You can look [here](https://github.com/xmartlabs/Eureka#custom-presenter-rows) but you don't need a custom row, just a custom view controller instead of `SelectorViewController`

**Comment by biskit** [comment]
Its a little more than that. Typically PushRow takes data from the row cell text and puts it on the page it pops up, in the header. I did not want that as I set the UITableViewCellStyle to .Default and updated the cell text instead of cell value.
Its once again pretty generic as you don't allow for .Default to handle the case. Pull available.

**Comment by mats-claassen** [comment]
I think there are ways to get around this by changing presentationMode, creating a custom SelectorRow or custom SelectorViewController.

Again. if somebody wants this functionality, we could have a look at it

**Comment by mtnbarreto** [comment]
@biskit i recommend you to take a look how the selector controller is shown by PushRow. By changing PushRow's `presentationMode` property value you can show another controller having complete control over it. The code of this new selector controller implemenented by you will look like pretty similar to `SelectorViewController` which Eureka provides.
