### ISSUE TITLE
Change font of different option labels in InlinePickerRow 

### ISSUE THREAD

**Issue by arr00** [xmartlabs/Eureka#534]
I am trying to make a Picker that shows all the available fonts on the device and the font name will be written in the that font. However, I can't figure out how to change the label font of the different options on the picker. Any help will be greatly appreciated!

**Comment by mats-claassen** [comment]
I don't know if a UIPicker supports that...
But this definitely has to do with UIPicker implementation and not Eureka. If UIPicker supports it you should be able to create a custom row to accomodate that logic. If UIPicker does not support it then you will have to implement it yourself.

**Comment by arr00** [comment]
@mats-claassen I understand that. I figured out how I could do that with the UIPicker delegate but I can't figure out how to implement delegates in a custom Eureka row.

**Comment by mats-claassen** [comment]
If I understand you, you want to create a custom row that implements UIPickers delegate?
Or do you want to implement the delegate from elsewhere?

In any case I think you should subclass `PickerCell` implementing your custom UIPicker. You should create a row very similar to `_PickerRow` that uses that cell.
And you should create your own `_PickerInlineRow` that uses your custom PickerRow.

**Comment by James-Coleman** [comment]
For the record I was able to do this by copying `PickerCell` and implementing `pickerView(_ pickerView: UIPickerView, viewForRow row: Int, forComponent component: Int, reusing view: UIView?)` instead of `pickerView(_ pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int)`.
In order to get the inline row to use the row I had to copy `_GCMIPickerViewRow` and `GCMIPickerViewRow` as well.
I found I couldn't subclass because `pickerRow` is private, is that right?
