### ISSUE TITLE
Help with customization

### ISSUE THREAD

**Issue by hdoria** [xmartlabs/Eureka#557]
Hi,

I'm having some troubles to customize my form. Is there a way to customize Eureka to have all the TextRows to be something like this:

![artboard_1](https://cloud.githubusercontent.com/assets/73786/16775979/8591a49e-4839-11e6-8769-469ec7a5e8f0.png)

I need to:

- Change the left and right margins
- Add border to all fields
- Add space between the fields

Thanks.

**Comment by mats-claassen** [comment]
@hdoria  Could you create rows with that style?

**Comment by hdoria** [comment]
@mats-claassen not yet. I have tried with defaultCellSetup, but it didn't work. I'm having problems with the left and right margins. :(

**Comment by mats-claassen** [comment]
One solution would be to subclass `FieldCell` and change its constraints by overriding `customConstraints`. Then you would have to create a subclass of that for every type of row you want to use, which is a bit of a downside but not more than like 100 lines of pretty repetitive code.

Another solution is changing `layoutMargins` of the cells. This is sometimes troublesome but I am sure you can get it done with that.

**Comment by adrianodiasx93** [comment]
![form](https://cloud.githubusercontent.com/assets/5974969/18281915/29d065f0-7435-11e6-9e7d-882c79dfc229.png)

I was able to reproduce the model. I subclassed the FieldCell class and overrode the method customConstraints @mats-claassen  as suggested (thanks for that). For the button I can add an UIButton as subview or use only the cell's textlabel. However, we still need to limit the area of the "click". I assume it's need some coding to change the methods to use only the textfields/subviews/textlabels instead of the whole cell, and perhaps it's not the best approach, so I'd love to hear some suggestions.

Thanks in Advance!!

**Comment by mats-claassen** [comment]
For the button I would use a footer on the section with a real UIButton so that the user gets the correct button tap animation. That also solves your "tappable area issue".

**Comment by codajustin** [comment]
Hi 
 Any chance you can provide an example how to properly subclass FieldCell to perform this type of customization?  Currently using 2.0.0-beta.1.

Thank you

**Comment by iOSUser110** [comment]
I have simple solution , Just change the tableview frame as below

 self.tableView?.frame = CGRect(x: 20, y: (self.tableView?.frame.origin.y)!, width: (self.tableView?.frame.size.width)!-40, height: (self.tableView?.frame.size.height)!)

**Comment by marciomeschini** [comment]
```cell.contentView.layoutMargins = whateverInsets```

**Comment by liorp** [comment]
Changing layoutMargins code example: 
After defining form, add
`for row in form.rows {
            row.baseCell.separatorInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        }`

**Comment by Coners** [comment]
MESSAGE TO ALL: 

These answers only work *if* you have done *other things* I fixed this issue (from start to finish) by doing [this](https://github.com/xmartlabs/Eureka/issues/723) I don't want to repost
