### ISSUE TITLE
How to control related rows?

### ISSUE THREAD

**Issue by Ssimboss** [xmartlabs/Eureka#602]
So, guys, here is the problem. I've got two values to be controlled via two rows. For example, diameter of circle & circumference of circle. Each value is controlled by DecimalRow. But how to bind these values on changing?

I' ve tried this:

```
form.last!  <<< DecimalRow("diameterTag") { row in 
    row.title = "diameter"
    row.value = 0.0
}.onChange{ row in
    let circumferenceValue = row.value? * 3.14
    let circumferenceRow = self.form.rowByTag("circumferenceTag")!
    circumferenceRow.value = circumferenceValue
    circumferenceRow.updateCell()
}
```
But this code caused a lot of bugs. Examples:

- When I'm trying to enter "56" to diameter-row, cell updates after user taps "5" on keyboard and cell outputs "5.0". So, user is pushed to delete ".0" and then tap "6". Cell will update value to "56.0".
- When I'm trying to enter  "1.06" to diameter-row, cell doesn't keeps that value. It will be rounded to "1.00" when other cell will become first responder.  

Bugs will disappear if you would just remove ".onChange" handler from code

**Comment by mats-claassen** [comment]
As you keep changing the value of the other row, the rows will keep calling their onChange methods back and forth. You could try changing the value of the other row `onCellUnhighlight` which would happen when the user leaves the row. (For this to work you will have to override `onCellHighlight` as well)
Or you have to implement something so that both row's `onChange` callbacks don't keep calling themselves.

**Comment by mtnbarreto** [comment]
As of Eureka 2.0.* `onCellHighlight` and `onCellUnhighlight` were renamed to `onCellHighlightChanged` callback. 
In order to check if the closure was invoked due to a highlight we can check row's `isHighlighted` boolean property.
