### ISSUE TITLE
Scroll to bottom of tableview on button event

### ISSUE THREAD

**Issue by alexvazquez** [xmartlabs/Eureka#607]
Hi, Im adding new elements to my form from a button that its on the very top. When the elements goes beyond the height of the screen, is there a way to force scroll to the bottom of the table view?

Thanks

**Comment by rdadkins** [comment]
This can be achieved pretty easily via `UITableView.scrollToRowAtIndexPath` and here is how you do it:
```
if let indexPath = self.form.rows.last?.indexPath() {
  self.tableView?.scrollToRowAtIndexPath(indexPath, atScrollPosition: .None, animated: true)
}
```
`atScrollPosition` can be changed to meet your requirements as well as being animated.

You are able to do this because FormViewController has a tableView that you can access, and thus scroll within it. And instead of `self.form.rows`, you can use `self.form.allRows`. The difference being is that `rows` only contain the visible rows (which may better suit your purpose).

**Comment by mats-claassen** [comment]
Thanks @rdadkins for helping out!
