### ISSUE TITLE
Question: how to add custom cells alongside form rows?

### ISSUE THREAD

**Issue by jadidian** [xmartlabs/Eureka#67]
hi, I was wondering what would be the best way to add rows (or cells) for layout stuff, like hero images or other views which don't provide any data for the form but should be a part of the underlaying table view. using XLForm I could just extend `XLFormBaseCell`, pass it a view and override its `layoutSubviews`, register it as a row and use it in the form; but I (still) have no idea how to do it with Eureka... any suggestions?

btw, thank you guys for the awesome job.

**Comment by jadidian** [comment]
UPDATE: for now, I did it like this:
```swift
final class CustomViewRow: Row<String, CustomViewCell>, RowType {
  required init(tag: String?) {
    super.init(tag: tag)
  }
}

class CustomViewCell: Cell<String>, CellType {
  var customView: UIView? {
    didSet {
      if let oldView = oldValue {
        oldView.removeFromSuperview()
      }
      if let newView = centerView {
        contentView.addSubview(newView)
      }
    }
  }

  required init(style: UITableViewCellStyle, reuseIdentifier: String?) {
    super.init(style: style, reuseIdentifier: reuseIdentifier)
  }

  override func setup() {
    super.setup()
    height = { ... }
    selectionStyle = .None
  }

  override func update() {
    super.update()
  }

  override func layoutSubviews() {
    super.layoutSubviews()
    if let customView = customView {
      customView.frame = CGRect( ... )
    }
  }
}
```
and then:
```swift
    form +++ Section()
      <<< CustomViewRow(" ... ")
        .cellSetup() { cell, row in
          cell.customView = UIImageView(image: UIImage(named: " ... "))
        }
```
however, it doesn't feel right to pass an arbitrary type `<String>` to the cell & row, and I'm not sure if overriding the `tableView(tableView: cellForRowAtIndexPath:)` method to create a custom cell and meddling with Eureka's index paths is a good idea.

**Comment by mtnbarreto** [comment]
@jadidian 
Why don't you use table view header footer or section header footer to show these views? https://github.com/xmartlabs/Eureka#section-header-and-footer 
Could you please provide examples where rows are better than section header and footers? 
I would like to discuss if it's worth creating a new row type to show views.

Regarding the Row String generic type needed, In eureka each type must extend from `<RowType, CellType>` and `RowType` should conforms to `Equatable` so it can't be `Void`.

*"I'm not sure if overriding the tableView(tableView: cellForRowAtIndexPath:) method to create a custom cell and meddling with Eureka's index paths is a good idea."* I think this is not a good idea since Eureka uses its own abstraction to represent table view cells.
