### ISSUE TITLE
Why do you want to delete imageRow ？

### ISSUE THREAD

**Issue by huangshuai-IOT** [xmartlabs/Eureka#688]
Excuse me, I do not know why you want to delete the imageRow,Can you explain to us？
In addition，I am using Swift3，I want to back the commits where the imageRow is alive , can you tell me the commits num?
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :commit => '????', :branch => 'Swift3'

**Comment by mtnbarreto** [comment]
ImageRow was included in example project, you can take the source files from there. 
We deleted it because even when we don't use it apple force us to declare a plist property explained here: #655. If you forget to add this apple reject your app.

We will provide it as a custom row under [EurekaCommunity](https://github.com/EurekaCommunity) organization. I really appreciate If you can do it :).

**Comment by mtnbarreto** [comment]
Quick solution is to add ImageRow, ImageCell and it's presenter view controller to your app project.

**Comment by mtnbarreto** [comment]
We have shared ImageRow in EurekaCommunity github organization as a Eureka plugin... https://github.com/EurekaCommunity/ImageRow
