### ISSUE TITLE
Unable to open multiselector as actionsheet way

### ISSUE THREAD

**Issue by vincentlkl** [xmartlabs/Eureka#730]
I am trying style my multiselector, I am not able to find extra documentation on it.

currently my code is:
form.last! <<< MultipleSelectorRow<String>() {
            $0.title = "ActionSheetRow"
            $0.selectorTitle = "Pick a number"
            $0.options = ["One","Two","Three"]
}

and the result is 

![actionsheet](https://cloud.githubusercontent.com/assets/2097251/19406714/d19c84a2-92bd-11e6-83d1-7103ade81208.gif)

Is there an option so that I can select multiple with opening the pop up box as selector but with multiple selector. Due to my user would prefer open up on option on the same page. 

![selector](https://cloud.githubusercontent.com/assets/2097251/19406724/1fde2e0e-92be-11e6-973f-ff1c19c7c7c2.gif)

**Comment by mtnbarreto** [comment]
There is no such multiple selector action sheet row. You should create a custom row. Follow the documentation and take a look at build in rows. 

Please make this kind of question on stackoverflow as contribution guide points out, you will have a better luck since the community eventually will help.

**Comment by mtnbarreto** [comment]
These blog posts may help: 

https://blog.xmartlabs.com/2016/09/06/Eureka-custom-row-tutorial/
https://blog.xmartlabs.com/2016/09/23/Eureka-custom-row-tutorial-2/
https://github.com/xmartlabs/Eureka#custom-rows
