### ISSUE TITLE
Invalide behaviour for validation 

### ISSUE THREAD

**Issue by chlebta** [xmartlabs/Eureka#800]
Hello, 
 I've noticed that row inside hidden section are validated, normally it should be like this : 
When row or section is hidden then ignore validation rules ?

**Comment by mtnbarreto** [comment]
Hi @chlebta , Are you talking about `form.validate()` method?

**Comment by pluckq** [comment]
How to achieve this feature in latest version? I'm using 2.0.0-beta.1, and there no includeHidden flag for validate(), only for values

**Comment by theGlenn** [comment]
@pluckq recent travis build failed https://travis-ci.org/xmartlabs/Eureka/builds/189216638, so the 
the last merges are not in sync yet with what you get from `pod install` so if you really need this feature now, you can (**at your own risks**) change your Eureka declaration like this:

`pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka', :branch => 'master' ` 

So that you will always be up to date with the last commits on master even is unstable. 

Or can you create this extension somewhere in your project:

```Swift
extension Form {
    
    @discardableResult
    public func validate(includeHidden: Bool = false) -> [ValidationError] {
        let rowsToValidate = includeHidden ? allRows : rows
        return rowsToValidate.reduce([ValidationError]()) { res, row in
            var res = res
            res.append(contentsOf: row.validate())
            return res
        }
    }
}
```
