### ISSUE TITLE
Possible to dynamically add options to MultipleSelectorRow?

### ISSUE THREAD

**Issue by jackcohen5** [xmartlabs/Eureka#836]
Just wondering if it is possible to dynamically add new options to a MultipleSelectorRow on the onChange callback without having to go back to the form and re-push the row?

For example to implement an "Add New" cell which creates a "New" option that can also be selected?

**Comment by santiagofm** [comment]
Hey @jackcohen5 !
You definitely can do this, here a snippet from the Example project with that implemented:
```swift
<<< MultipleSelectorRow<Emoji>() {
    $0.tag = "emojiSelector"
    $0.title = "MultipleSelectorRow"
    $0.options = [💁🏻, 🍐, 👦🏼, 🐗, 🐼, 🐻 ]
    $0.value = [👦🏼, 🍐, 🐗 ]
}
.onPresent { from, to in
    to.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: from, action: #selector(RowsExampleViewController.multipleSelectorDone(_:)))
}
        
<<< ButtonRow() {
    $0.title = "add"
}
.onCellSelection { [weak self] _, _ in
    guard let me = self else { return }
                    
    if let row = me.form.rowBy(tag: "emojiSelector") as? MultipleSelectorRow<Emoji> {
        row.options.append(🍐)
    }
}
```

Cheers

**Comment by luisgizirian** [comment]
Thanks @mats-claassen! I'm going nuts on this one. I'll give a try on your suggestions.

**Comment by luisgizirian** [comment]
First, congratulations on putting together this sweet library! So happy you came up with Eureka! :)

Now let me better explain what I'm trying to achieve: once a MultipleSelectorRow<T> gets presented and materializes itself, I'm trying to add a new value to the presented on screen list. This is different from the above sample, that adds *option* right from enclosing form.

The way I've done it, is by righting a UIBarButton into presented sub-form/selectable-list, that sets a new value from user's input, by adding it both to persistent storage (a mutable array below, but a Core Data List in real life), and UI.

Two things:
* I'd like to replace the user's input collection, replacing the Alert with text input with a search bar with adding capabilities (perhaps extending on this one: http://bithavoc.io/blog/2016/07/04/eureka-search-push-row/). Future work
* Is it possible somehow to insert new rows at top, instead of appending them at bottom? Initial set will be visible/usable, but as the list grows, new values will get pushed at bottom (off-screen), forcing the user to swipe down to check.

Here, some pseudo-code of what I've done. If further clarification's required, let me know.

(sorry I'm extending over this closed issue. please let me know if you'd prefer otherwise)
```
class EditorViewController: FormViewController {
var controller: FormViewController?
// mutable array...
var countries: [String] = ["US", "UK", "Uruguay", "Uganda"] 

// Then, at viewdidload time...
// [...]
form
            +++ Section("Otras propiedades")

                <<< MultipleSelectorRow<String>("countries") { row in
                    row.title = "Tags"
                    row.selectorTitle = "Tags"
                    row.value = treatSet
                    row.options = countries.map { $0 }
                    row.onPresent { from, to in
                        self.controller = to
                        to.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .add, target: from, action: #selector(EditorViewController.addElement(_:)))
                    }
                }
// [...]
@objc func addTreatment(_ item:UIBarButtonItem) {
        let alert = UIAlertController(title: "New Country",
                                      message: "Add a country here",
                                      preferredStyle: .alert)
        let saveAction = UIAlertAction(title: "Save", style: UIAlertAction.Style.default) { (action) in
            guard let textField = alert.textFields?.first,
                let nameToSave = textField.text else {
                    return
            }

            countries.insert(nameToSave, at: 0)
           
            let newRow = ListCheckRow<String>()
            newRow.title = nameToSave
            newRow.selectableValue = nameToSave

            // This add a new row at bottom, is is possible to top it?
            self.controller?.form.first?.append(newRow)
            //
        }
        let cancelAction = UIAlertAction(title: "Cancel",
                                         style: .default)
        
        alert.addTextField()
        
        alert.addAction(saveAction)
        alert.addAction(cancelAction)
        
        self.controller?.present(alert, animated: true)
    }
}
```

**Comment by mats-claassen** [comment]
@luisgizirian Every PresenterRow (like `MultipleSelectorRow`) has a `presentationMode` which defines how it is presented. You can change this to return your own view controller. This means you can subclass the `MultipleSelectorViewController` which is used for `MultipleSelectorRow` and implement all the logic in that subclass (this is so that you don't have to handle actions of that view controller in another view controller)

You can do this by doing something like this (change the generic parameters to whatever fits your needs):

```swift
open class AAA: MultipleSelectorViewController<GenericMultipleSelectorRow<String, PushSelectorCell<Set<String>>>> {
    override public init(nibName nibNameOrNil: String? = nil, bundle nibBundleOrNil: Bundle? = nil) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }

    public required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
}
```

You would then have to set the `presentationMode` of your `MultipleSelectorRow` to this:
 ```swift
row.presentationMode = .show(controllerProvider: ControllerProvider.callback {
            return AAA() as! MultipleSelectorViewController<GenericMultipleSelectorRow<T, PushSelectorCell<Set<T>>>>
            }, onDismiss: { vc in
                let _ = vc.navigationController?.popViewController(animated: true)
        })
```


As for adding rows at the beginning of a section, use the methods you would use on any array-like type, for example `section.insert(row, at: 0)`

**Comment by luisgizirian** [comment]
I'll subclass as you suggest to implement our custom logic in isolation. Regarding array's insert method, I'm getting a mutability error, but let's leave that for the future as I'm developing bits on top of a beta release.

Thanks for your help @mats-claassen!
