### ISSUE TITLE
Swift 3.1 version

### ISSUE THREAD

**Issue by felipeplets** [xmartlabs/Eureka#904]
Hello guys, 

Due to the update to [Swift 3.1](https://github.com/apple/swift/blob/master/CHANGELOG.md) for Xcode 8.3 I've started to play with it and see what I would need to migrate. The main resource I see needs to be updated is Eureka. 

I already started the conversion on my own fork but would like to ask for a branch swift3.1 on the main repo so I can create the PRs for the right place. 

P.S.: Is this the best channel for this? Is there a chat room (HipChat, Slack, etc... ) for Eureka developers? 

All the best, 
Plets

**Comment by mtnbarreto** [comment]
Hi @felipeplets , yes, let's continue any Eureka conversation in this thread or any other repository issue. 
Here you have the new branch https://github.com/xmartlabs/Eureka/tree/swift3.1

Thanks for helping in the migration!

**Comment by thebluepotato** [comment]
If you refer to this issue https://github.com/realm/realm-cocoa/issues/4586, you'll see that the encountered build errors are a Swift bug. It's been fixed in the latest Swift 3.1 snapshot and Eureka compiles fine in its 2.0.0-beta1 release. It didn't make Xcode 8.3 beta 2 but will be in beta 3 so I guess the new branch is superfluous. Swift 3.1 is made to be source-compatible with Swift 3.0 and incompatibilities should be reported as bugs according to the release notes.

Cheers!

**Comment by m-revetria** [comment]
Closing this, Eureka has been released with support for Swift 3.1 some time ago.

**Comment by mtnbarreto** [comment]
@m-revetria readme requirements doc section should be updated indicating to use Xcode 8.3.x which has support for swift 3.1.
