### ISSUE TITLE
Placeholder customisation?

### ISSUE THREAD

**Issue by calebmanley** [xmartlabs/Eureka#905]
Hi,

I've noticed you can change the placeholder text colour in certain rows like decimal rows, but you cannot change it in PickerInputRows or DateRows. Would be great if it was a feature of the base `Row` class so it could be changed in `.defaultCellUpdate`

**Comment by mtnbarreto** [comment]
Not every cell property is exposed from its correspond row. To set up the less common cell properties, you should access the cell and set up it property from `cellUpdate` or `defaultCellUpdate`. Take into account that the cell instance is passed as an argument to these callbacks. 

Let me know if it works.

**Comment by calebmanley** [comment]
![screen shot 2017-01-31 at 5 51 19 pm](https://cloud.githubusercontent.com/assets/2014573/22455031/fff8faea-e7dd-11e6-8044-2273299619a1.png)
![screen shot 2017-01-31 at 5 51 42 pm](https://cloud.githubusercontent.com/assets/2014573/22455030/fff86aa8-e7dd-11e6-91cc-c77bfa61a3c7.png)

I am trying to change it in `defaultCellUpdate` but can't.
See screenshots for example...

**Comment by mtnbarreto** [comment]
I was able to change it. See the attached image..

<img width="785" alt="screen shot 2017-02-01 at 11 36 19 am" src="https://cloud.githubusercontent.com/assets/1746532/22510982/cd4eb158-e872-11e6-9eaf-76e0ef0ffa18.png">

Notice that i need to disable  useFormatterDuringEditing to make the textField empty when deleting characters. Otherwise the textField don't become empty. 

I'm using master branch version but it should also works in 2.0.0 beta version.
