### ISSUE TITLE
Custom Section

### ISSUE THREAD

**Issue by igordeoliveirasa** [xmartlabs/Eureka#939]
Any tip if I wanted to create a custom section with a right button?

**Comment by fedeojeda95** [comment]
Hi @igordeoliveirasa 

Are you trying to create a section with a custom right button in the header? This can actually be achieved easily. 

In order to achieve this, you can use a custom view:

From a .xib file:

```
Section() { section in
    var header = HeaderFooterView<MyHeaderNibFile>(.nibFile(name: "MyHeaderNibFile", bundle: nil))

    // Will be called every time the header appears on screen
    header.onSetupView = { view, _ in
        // Commonly used to setup texts inside the view
        // Don't change the view hierarchy or size here!
    }
    section.header = header
}
```

Or a custom UIView created programmatically

```
Section(){ section in
    var header = HeaderFooterView<MyCustomUIView>(.class)
    header.height = {100}
    header.onSetupView = { view, _ in
        view.backgroundColor = .red
    }
      section.header = header
}
```

For further information and other ways to create the header with a custom view, please refer to the documentation to the [Section Header and Footer section](https://github.com/xmartlabs/Eureka#section-header-and-footer)

Hope it helps! Regards,

**Comment by m-revetria** [comment]
Closing this due to lack of response
