### ISSUE TITLE
Text Should Change Equivalent?

### ISSUE THREAD

**Issue by clayellis** [xmartlabs/Eureka#969]
Is there a way to prevent certain characters from being entered similar to a `UITextFieldDelegate` `shouldChangeCharacetersInRange`? The closure validation helps, but still doesn't prevent users from actually entering the invalid characters.

**Comment by fedeojeda95** [comment]
Hi @clayellis 

I assume you are talking about using the `TextRow`, am I right? In the case of what you are trying to achieve, I believe the best option would be to go with a simple custom row. You can have a new row that inherits from `FieldRow<YourTextCell>`. 

`YourTextCell` (just a placeholder name) would be subclass of `TextCell`, which already has all the logic and UI setup for the textField (it's the cell used by the `TextRow`).

In `YourTextCell`, since you are inheriting from `TextCell`, and `TextCell` inherits from `_FieldCell<String>`, which conforms `UITextFieldDelegate`, you can implement the method `func textField(_ textField: UITextField, 
shouldChangeCharactersIn range: NSRange, 
      replacementString string: String) -> Bool` in `YourTextCell`.

Hope it helps! Feel free to further ask. Regards,

**Comment by clayellis** [comment]
Thank you much! I'll probably go back and swap out my hack for your suggestion. Cheers!
