### ISSUE TITLE
Multivalued section does not display image in imagerow

### ISSUE THREAD

**Issue by ryoid** [xmartlabs/Eureka#977]
iOS: 10.0+
Xcode: 8.2.1
Eureka: Latest from git

Testing out the multivalued section feature, however it seems that when it is used with [ImageRow](https://github.com/EurekaCommunity/ImageRow) the image does not display even when it is actually set. 

![screen shot 2017-03-31 at 10 45 34 am](https://cloud.githubusercontent.com/assets/18044529/24534302/a4316cec-15ff-11e7-86a1-c052f487fb5c.png)

**Comment by barbourkd** [comment]
I'm having the same problem. I think it is because the MultivaluedSection is setting the detail accessory on the row and it's replacing the image preview. Haven't been able to find a workaround to make it show up.

**Comment by santiagofm** [comment]
Hey guys !
After you pick an image it gets set to the cell's `accesoryView` to show, but when the row is in a `MultivaluedSection` the reorder control takes the cell's `accesoryView` space and so the image isn't showed.
A way to fix this would be to set the image to the cell's `editingAccesoryView` also so that when the tableView is in the edit mode, the image is still shown.

Cheers
