### ISSUE TITLE
MultivaluedSection is not there!

### ISSUE THREAD

**Issue by mohammdsss1** [xmartlabs/Eureka#979]
I am using Eureka through CocoaPods, here is my pod file:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "POSRocket" do
    pod 'Eureka'
end
```

But when I run pod install and then check Section.swift; I can't find 'MultivaluedSection' provided in the example.

Also whenever I use pod 'Eureka', '~> 3.0' and run pod install it gives me an error in the teminal said:
Unable to satisfy the following requirements

**Comment by FranciscoAmado** [comment]
Hey there,

I'm not from the Eureka team but I believe MultivaluedSection's aren't already available in an official release.

> Also whenever I use pod 'Eureka', '~> 3.0' and run pod install it gives me an error in the teminal said:
Unable to satisfy the following requirements

This is happening because you're targeting a non existing version of the pod, current latest release is [2.0.1](https://github.com/xmartlabs/Eureka/releases/tag/2.0.1)

if you wan't to have access to MultivaluedSection's you can target your pod to the master branch for now
`pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git'`

**Comment by mtnbarreto** [comment]
It will be available in the next official release. 
Follow @FranciscoAmado advice to use Multivalued sections feature for now.

**Comment by mohammdsss1** [comment]
Thanks @FranciscoAmado

**Comment by TCOA** [comment]
I've just looked to add MultivaluedSection to my app, and took the advice given.  The response to pod install I get is 
`Pre-downloading: `Eureka` from `https://github.com/xmartlabs/Eureka.git`
[!] Unable to satisfy the following requirements:

- `Eureka (from `https://github.com/xmartlabs/Eureka.git`)` required by `Podfile`
- `Eureka (~> 2.0.0-beta.1)` required by `ImageRow (1.0.0)``

Any way to get both of these at the same time?

**Comment by santiagofm** [comment]
hey @TCOA, we've released a new version of `ImageRow` that requires Eureka 3.0.0. Please run `pod repo update` to update cocoapods specs, remove the contraint to `ImageRow` 1.0.0 and retry `pod install`!
Cheers

**Comment by TCOA** [comment]
Thanks @santiagofm for the fast reply!

After several attempts, I have things running now and can get started on working with MultivaluedSection!

For others that may have 'newbie' sort of issues, here is what I had to clear up.....

running `pod repo update`, I got an error of 
`warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2204 and retry the command.`

I searched and got a command to use in Terminal on my computer from [this link](https://stackoverflow.com/questions/7830728/warning-on-diff-renamelimit-variable-when-doing-git-push) and then `pod repo update` again with no errors.

in the Pod file, change `pod 'ImageRow', '~> 1.0'` to `pod 'ImageRow'` (I learned that is what "remove the constraint" means...) and `pod install` again.

It will install a new ImageRow (2.0.0) and all looks great!
