### ISSUE TITLE
IOS: Is it Possible to add custom PopoverSelectorRow? 

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [xmartlabs/Eureka#995]
Hi there,

 I have read the Eureka documents, it's provided how to add the `Custom Rows` to Eureka. I have also tried with `<LabelRow>` and others.
But, i am unable to add custom `PopoverSelectorRow`. Please help me out.

Thanks.

**Comment by m-revetria** [comment]
Hi @ThiyagarajanShivSankaran,

You can make your custom `PopoverSelectorRow` in the same way that you would make any other custom row. In concrete you have to make your custom row to inherit  from `_PopoverSelectorRow` passing your custom cell.

Take a look to the next snippet to see how you can achieve a custom popover row, it's a very simple example but I illustrate what needs to be done:

```swift
class MyCustomCell: Cell<String>, CellType {

    // I created a nib file with a label and an image view within a UITableViewCell of type `MyCustomCell` and connected these subviews to my outlets below
    @IBOutlet weak var backgroundImageView: UIImageView!
    @IBOutlet weak var label: UILabel!

    required public init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
    }

    required public init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }

    override func update() {
        super.update()
        self.label.text = self.row.value ?? "Select a value"
    }
}

final class MyPopoverSelectorRow: _PopoverSelectorRow<MyCustomCell>, RowType {
    public required init(tag: String?) {
        super.init(tag: tag)
        cellProvider = CellProvider<MyCustomCell>.init(nibName: "MyCustomCell")
    }
}

// .......
// Next you can add the new row in your view controller like any other:
// .......
form.last! <<< MyPopoverSelectorRow() {
    $0.options = ["option 1", "option 2", "option 3"]
    $0.value = "option 1"
    $0.selectorTitle = "Choose an Emoji!"
}
```

And the result may look like:
![issue_995](https://cloud.githubusercontent.com/assets/4791678/26474990/03cf881c-418b-11e7-8ffd-7ba439fbcd6b.gif)

-----------------

Otherwise, we use our GitHub project for bug reports and feature requests. In the future, you should open questions like this on Stack Overflow and tag eureka-forms.

**Comment by ThiyagarajanShivSankaran** [comment]
@m-revetria thank you for your reply. Your example is really helpful for me.
